
import { LibraryItem, StaffMember, PartnerItem, ProxyItem } from './types';
import { MANGA } from './mangaData';
import { MOVIES } from './movieData';
import { TV_SHOWS } from './tvData';
import { ANIME } from './animeData';

const getSearchLink = (title: string) => `https://drive.google.com/drive/search?q=${encodeURIComponent(title)}`;
const getPlaceholderImg = (title: string) => `https://placehold.co/600x900/1c1c1f/3f3f46/png?text=${encodeURIComponent(title.replace(/[:\s]/g, '+'))}&font=playfair-display`;

// --- MASSIVE LINK DATABASE EXTRACTED FROM PDF ---
const LINK_DB: Record<string, string> = {
  // Movies
  "A Charlie Brown Christmas": "https://drive.google.com/file/d/1e2UIrJdsz_0k5tp2v0EnPZiPv2ZQSTzg/view?pli=1",
  "Avengers Endgame": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Ant-Man": "https://drive.google.com/file/d/1AW3Zm8256tzZ-37lmgYmIGse4knu8IdA/view",
  "Ant-Man and The Wasp: Quantumania": "https://drive.google.com/file/d/1AW3Zm8256tzZ-37lmgYmIGse4knu8IdA/view",
  "Avengers Infinity War": "https://drive.google.com/file/d/1oKDbw6zCdSRKRbABn6nKf_4LGsA3ftwL/view?usp=sharing",
  "A Goofy Movie": "https://drive.google.com/file/d/1ify_EMaQW-ZAn2F0STztn2AGU-jE7aHL/view",
  "An Extremely Goofy Movie": "https://drive.google.com/file/d/1e4NzmeC84qest_9Wzmtvmi80brGPYnsN/view?usp=sharing",
  "Alvin and the Chipmunks 2007": "https://drive.google.com/file/d/1uCRRJZj1GAaweX996uHbF2zxPoessmGW/view?usp=share_link",
  "Alvin and the Chipmunks: The Squeakquel": "https://drive.google.com/file/d/1em55qHTtdrWD4Dox9CXs9r1042TLu_cu/view?usp=share_link",
  "Alvin and the Chipmunks: Chipwrecked": "https://drive.google.com/file/d/1LTKy48IbusfXsl5nSNDTd0M3A8B3aPke/view?usp=share_link",
  "Alvin and the Chipmunks: Road Chip": "https://drive.google.com/file/d/1ljX4FCKuoIuDR-hcH3J97hZ21Os_4C3W/view?usp=drive_link",
  "A Christmas Story": "https://drive.google.com/file/d/1nz29MUfftWx_MeBVh4Bn7TVXlUy_6BH2/view?usp=drive_link",
  "Annie": "https://drive.google.com/file/d/1GYQqHUdyWMNQJKj4Sa8SGW0ZRX32D5og/view",
  "A Bugs Life": "https://drive.google.com/file/d/1AIq4OqiMWiY9zZSayF5VID7pfTwSH6BM/view",
  "A Christmas Carol": "https://drive.google.com/file/d/1hi5sfVVAYK5AsMis11QjD5JLvL5aUY0h/view?usp=drive_link",
  "Batman": "https://drive.google.com/file/d/1P8z8U0j5UHxqTq0taTj18TgG6nZwSKYd/view",
  "Batman Returns": "https://drive.google.com/file/d/1aeYtz38ljtxCCtuVs4x0zuUh2TWKf-K6/view",
  "Batman Forever": "https://drive.google.com/file/d/1YFYuZeG8EXxNkPdB7jIIGOFm7ULi349r/view",
  "Batman & Robin": "https://drive.google.com/file/d/1uMzsWkDLeiE0X7M0rm5EUUx3y26yzhc2/view",
  "The Dark Knight Rises": "https://drive.google.com/file/d/1ssHaJjHmu-V5fTC4_AoyABD_KYB1dkNX/view",
  "Batman Begins": "https://drive.google.com/file/d/1ZegfkrD50sGDUVJ-4d9IiBpR0MTmdphx/view",
  "Black Panther": "https://drive.google.com/file/d/1wdUOiz7tI3R5vTz779h7CesAW5h0kUh1/view",
  "Black Panther: Wakanda Forever": "https://drive.google.com/file/d/198qUcefIK54KnZzxAx6_L8u7l37oCfhK/view",
  "The Batman 2022": "https://drive.google.com/file/d/16si_yvGyZn5mgvNIHil5xXOR3I8RaTKb/view?usp=sharing",
  "The Dark Knight": "https://drive.google.com/file/d/1CZvw1MgSLVQR9Z9L8qpl8j1oI7DnMDWr/view",
  "Batman: The Return of the Joker": "https://drive.google.com/file/d/1wEmEjdaO0dp1nonCewG8URl6YsQOk0ru/view",
  "Beetlejuice": "https://drive.google.com/file/d/1fs2-oBGADuUeepkLX2V3zxNNUstHvBTs/view?usp=sharing",
  "Beetlejuice Beetlejuice": "https://drive.google.com/file/d/1OsCtW4NUV94utDNxmFejUFoH6euf8Ind/view?usp=sharing",
  "The Boss Baby": "https://drive.google.com/file/d/1PapBJzYo5d6QoK8sFA71ksVkdjYfud2V/view?usp=drive_link",
  "The Boss Baby: Family Business": "https://drive.google.com/file/d/1aiZMcnKPiHlmK9D0HpQRKd-SueENFFFC/view?usp=drive_link",
  "The Bad Guys": "https://drive.google.com/file/d/1Ep4I8JdvH8NlbcqxiNMA8c7U_UAOpewT/view",
  "Bad Boys 2": "https://drive.google.com/file/d/14i4ehISzm0r3u-zjYK5BdHBUSTEqCb8z/view?usp=sharing",
  "Blue Beetle": "https://drive.google.com/file/d/1T2XMXtDAlohPcGdi-u2p9zXF9Os9zkY1/view",
  "Back to the Future": "https://drive.google.com/file/d/1RvzJFPZbr-jM8EKjMFUb56QLDHQ4LTBV/view?usp=drive_link",
  "Barbie": "https://drive.google.com/file/d/1K88LvZ6q9KRwsdiVQ72Wrh5DQqWVLkd3/view?usp=sharing",
  "Birds of Prey": "https://drive.google.com/file/d/1AShi8tLLzbPiPO6vDokf8ew-qBbzh5Pb/view?usp=sharing",
  "Boyz N The Hood": "https://drive.google.com/file/d/1fCv2dJuy8k_NQWAxbNRxqW0_zKetF-uy/view",
  "The Blackening": "https://drive.google.com/file/d/1VBG7WXqeiZ3BSvPuWUPCL1_iF9znvPI5/view?usp=sharing",
  "The Black Phone": "https://drive.google.com/file/d/140S8bCV6Ht2WticzegM_jfRayS2_Mvn_/view?usp=sharing",
  "The Black Phone 2": "https://drive.google.com/file/d/1Nnkb35gi9f-jc4LvwVDUq8MTLur7mK3L/view?usp=sharing",
  "Coraline": "https://drive.google.com/file/d/1TFiL16cNmQmG5pSi-s6od4xgymFqK1kJ/view",
  "Captain America: Civil War": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/captain-america-civil-war",
  "Creed": "https://drive.google.com/file/d/1w9nVBGOKDax-xCr-caqekW4hcjRUQWZA/view?usp=drive_link",
  "Creed 2": "https://drive.google.com/file/d/1KnW-KW6LV-fH0S0R_2sbsEKkKhSFK-OP/view",
  "Creed 3": "https://drive.google.com/file/d/1j8pGyNx9PHk_Gicns9JlDaX82qBIi1_m/view?usp=drive_link",
  "Coco": "https://drive.google.com/file/d/194M4dGCwh1hTxVM1-_axnLSdt4trnbK2/view?usp=sharing",
  "Cars": "https://drive.google.com/file/d/1RoWQ2LZecPYvsZ48Sah7_xBvZzEHcXL1/view?usp=drive_link",
  "Cars 2": "https://drive.google.com/file/d/1YinG1kmgSqWI5kQwfDsQO6vK1xzM6K7o/view?usp=drive_link",
  "Child's Play": "https://drive.google.com/file/d/1FPO2K8Oqb1O3qm1qb57NhZHhaGCvQjAz/view?usp=sharing",
  "Child's Play 2": "https://drive.google.com/file/d/1NXrR22Ja1iaa3PcidheWe6dKmK80A2em/view?usp=drive_link",
  "Bride of Chucky": "https://drive.google.com/file/d/1bdeH-TLFYRBpC0sp3eIWNGocKlqPp5mw/view?usp=drive_link",
  "Child's Play 2019": "https://drive.google.com/file/d/1D-j3sPp4-DQmHs_Ce9Nxya0GnyAmEAQM/view?usp=drive_link",
  "Corpse Bride": "https://drive.google.com/file/d/1AHqrYm4cItyiEquPHJV5z3H81Cc0cCfI/view?usp=sharing",
  "Captain Underpants": "https://drive.google.com/file/d/1BW7yv_y4uk99Nsjbc--z1beQ_bYYmUXk/view?usp=share_link",
  "Seed of Chucky": "https://drive.google.com/file/d/1ibotaqumpENLsX67ZGbKzZcAStYmezqs/view?usp=drive_link",
  "Curse of Chucky": "https://drive.google.com/file/d/1iREiS873cIR4Wq3nKV-uBwaJVWbqIZe0/view?usp=drive_link",
  "Cult of Chucky": "https://drive.google.com/file/d/1JHK4oNMMg_RLU-IfCRkIA6L-1T9BJEVd/view?usp=drive_link",
  "Child's Play 3": "https://drive.google.com/file/d/1gEP2FcL30yLVaUw_J9As7Jum_rJPZlDt/view",
  "Coat of Many Colors": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/dolly-partons-coat-of-many-colors",
  "Circle of Love": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/dolly-partons-christmas-of-many-colors-circle-of-love",
  "The Conjuring": "https://drive.google.com/file/d/1i3WiDufrutDICVMnzJI0SYHQirwU0MIR/view?usp=sharing",
  "Detective Pikachu": "https://drive.google.com/file/d/1q5wcbuy536XQKTBAF7ImApMAlNMVHM5T/view",
  "Diary Of A Wimpy Kid: Rodrick Rules": "https://drive.google.com/file/d/1rKRsgdNioFs3rtkZai7Gz97FtAX0jdJ_/view",
  "Diary of a wimpy kid: dog days": "https://drive.google.com/file/d/0B6fv-OkwXRTzZ090UHlWcHY2dkk/view?usp=drivesdk&resourcekey=0-TgoMzBEyMorySYhDqB9uGA",
  "DND Honor Among Thieves": "https://drive.google.com/file/d/1iX6QbaV3Oi_yGDvqRcFvrJ4_gzIOisnT/view",
  "Despicable Me": "https://drive.google.com/file/d/1upRWBqPKcQjviBjAgYkzkWZuVjQ1SAWF/view",
  "Despicable Me 2": "https://drive.google.com/file/d/1eoQmOkUsxF0UwnQ0of-kmAlMMEhnKuzW/view?usp=sharing",
  "Despicable Me 3": "https://drive.google.com/file/d/1O9r7jbQZEgf58oKsOfI34z30XwRF_CI4/view?usp=sharing",
  "Despicable Me 4": "https://drive.google.com/file/d/1ggXkdigLOzQQgelB8exwzjVFb8bbef7d/view?usp=drive_link",
  "Descendants: The Rise of Red": "https://drive.google.com/file/d/14uIYHn4xepm1GLF2USxyBkUE6nQfueoE/view?usp=sharing",
  "Deadpool": "https://drive.google.com/file/d/1XUjU4fhDH7qpPEg_me8vlMba1uelRIwj/view?usp=gmail",
  "Deadpool 2": "https://drive.google.com/file/d/1wcE3D19t54BnWtLNl5cruklfPVPh92nY/view?usp=gmail",
  "Deadpool and Wolverine": "https://drive.google.com/file/d/1B_eiKUt7N5OxyUN9c37LG0pxcErP4yJ6/view?usp=drive_link",
  "Dune Part 2": "https://drive.google.com/file/d/14VeNSqVtt5gcibZOfjPcjkBoasPrpiEG/view?usp=drive_link",
  "Dogman": "https://drive.google.com/file/d/1sy0E41GNhba6yPMdC62cvjaTl_VtjJaz/view?usp=sharing",
  "The Mighty Ducks": "https://drive.google.com/file/d/1MKL3dbjVCDH4cmnPtBoT8SeQeoK8bRYN/view?usp=drive_link",
  "D2: The Mighty Ducks": "https://drive.google.com/file/d/1xqucoWKrHYKgkPtIH504nV_QWrezUcC9/view?usp=drive_link",
  "Elf": "https://drive.google.com/file/d/1-cJP_6uvuboesHkiYPgfIg49eKvsBsF0/view?usp=sharing",
  "8 Mile": "https://drive.google.com/file/d/13KF2oQ-b1WRvbjL0vMMAMlI0Vj8TYBuM/view?usp=sharing",
  "Free Guy": "https://drive.google.com/file/d/1EupGpY5FUCfaHtBUeSpf5PilmLHbjImJ/view?usp=sharing",
  "Friday": "https://drive.google.com/file/d/1SKE9sQ-DnHRRVGxU10Qk2QJ1Ws2jvv5M/view?usp=share_link",
  "Finding Nemo": "https://drive.google.com/file/d/1jP7PoHapLf_S_n75Afdc0RvzSwRqPcwm/view?usp=sharing",
  "Friday the 13th": "https://drive.google.com/file/d/1Tu0WxRUC-gADzYFEnSvudZ3MZ7Y735jH/view?usp=drive_link",
  "Friday the 13th Part 2": "https://drive.google.com/file/d/1ROenMVwRyMGW0EIsf4Xg67EvRAAT5kcX/view?usp=drive_link",
  "Friday the 13th Part 3": "https://drive.google.com/file/d/1Ak82TmSBG3_lpbUgsDq22AcZ5gzGvTTB/view?usp=drive_link",
  "Friday the 13th: The Final Chapter": "https://drive.google.com/file/d/1M2OD-EPO3AjkzwYNvJLXCNe4B7y6bmM6/view?usp=drive_link",
  "Friday the 13th Part V": "https://drive.google.com/file/d/1cB43qNpCCf90tHch87EC4hBywV0Ao5-V/view?usp=drive_link",
  "Friday the 13th Part VI": "https://drive.google.com/file/d/1Yug3RMr7f8z5P7TjxWgRN0geoWL7UnU4/view?usp=drive_link",
  "Friday the 13th Part VII": "https://drive.google.com/file/d/1CG5Te-vXcvPrEuJtQsN3HZigm6bz33Os/view?usp=drive_link",
  "Friday the 13th Part VIII": "https://drive.google.com/file/d/1oRePBRxnrhk8feVEE3OtTNnE0Y70a4ZN/view?usp=drive_link",
  "Jason X": "https://drive.google.com/file/d/1f_m_NTsYbbVFh1FBqXC1TOuS_4Yp6uSd/view?usp=drive_link",
  "FNAF": "https://drive.google.com/file/d/1TP307H3VaMznYmG5GDP08hByFMSvQ576/view?usp=sharing",
  "FNAF 2": "https://drive.google.com/file/d/1sJKwqO53RZFCVr32rNHeG-Z9cCxOm2ps/view?usp=sharing",
  "Frozen": "https://drive.google.com/file/d/1XIuN4Zp35mW0iN4p0ME5APxH18-6Zqft/view?usp=drive_link",
  "Frozen 2": "https://drive.google.com/file/d/1hpUpKEdeT9ta-8FjSpMUAXw17E-8uwIY/view?usp=drive_link",
  "Gran Turismo": "https://drive.google.com/file/d/1YnnYFC1P_MwgxavCoYtMvHOr_PoZAFNd/view?usp=sharing",
  "Guardians of the Galaxy Vol. 3": "https://drive.google.com/file/d/1pFavPs7Mi9rx_BrAjxbeHNWg7ClAB2_K/view?usp=sharing",
  "Good Burger": "https://drive.google.com/file/d/1jucPocCb8aq23Bh-GFLcniAk-k5UU-wC/view",
  "Good Burger 2": "https://drive.google.com/file/d/1TOjPbqSF5UqnPrn1zFqEWvkUeBNiyMax/view?usp=drive_link",
  "Ghostbusters": "https://drive.google.com/file/d/1Kur_TXv1AOx8hhs0qGc_IwZXKmWvD6Y7/view",
  "Grease": "https://drive.google.com/file/d/1W77S931ShuhZ2RVeiNrfdQQUcR4pKsD0/view?usp=drive_link",
  "Garfield": "https://drive.google.com/file/d/1g_YZyeIbjua21PNL4ZLfeIzJx-givpPE/view?usp=sharing",
  "Get Out": "https://drive.google.com/file/d/1NAL07bOQPidzTFNMSrccqr53PGag6nn2/view?usp=sharing",
  "Garfield 2004": "https://drive.google.com/file/d/1xMRDhscsmtcrECXXuOsqpAADTHJ0FxGS/view",
  "Hidden Figures": "https://drive.google.com/file/d/1sfjv_SEQZQ4QPgPAeS8xckKHORr3gLiG/view",
  "Home": "https://drive.google.com/file/d/1PvzOPEZp09GjSj3PEDuxb0Y1ceQvo1AX/view",
  "Home Alone": "https://drive.google.com/file/d/1l7dSSnBmw9Fnku5lxl7zYk7CsQa4JU3d/view?usp=sharing",
  "Home Alone 2": "https://drive.google.com/file/d/1sH3RXs-OiYr7ROKCtmB5miWVpX9G2b4Q/view?usp=drive_link",
  "Hotel Transylvania": "https://drive.google.com/file/d/1gZ4FVX5GLCSv2-i_sabXWhgl9u_3FeOB/view",
  "Hotel Transylvania 2": "https://drive.google.com/file/d/1LZI5E52J_R_Cx6f3EXLl-BAn6vuhUduD/view",
  "Hotel Transylvania 3": "https://drive.google.com/file/d/1aS3rHee1w5zNTGGmSFM57DSVlC1hSvIs/view",
  "Hotel Transylvania 4": "https://drive.google.com/file/d/1_Ujbv8ONdcmV8TrYw8WzTwdD93deiiZp/view",
  "Hercules": "https://drive.google.com/file/d/1sXad7VvXVn7qIilwdspq5RtjmInpa7mQ/view?usp=sharing",
  "Halloween": "https://drive.google.com/file/d/1yVnAsKg54Azo88VHYiKf4lDjtZ2ppVRr/view?usp=drive_link",
  "Halloween 2": "https://drive.google.com/file/d/1XnD--5UU_jD39fcTz0s3Wv1NCsO6In3r/view?usp=drive_link",
  "Halloween 3": "https://drive.google.com/file/d/1GoVr9RTnGTf9CXHHUUbbInxYcY9kmmrw/view?usp=drive_link",
  "Halloween 4": "https://drive.google.com/file/d/17ZJ5MBDP0jHzVd6roUI6zHkQzyYi_yY7/view?usp=drive_link",
  "Halloween 5": "https://drive.google.com/file/d/1Wz87fusvhrIyuHY3fdsBYY5Ytup-_ab4/view?usp=drive_link",
  "Halloween 6": "https://drive.google.com/file/d/1WLc07J82YQSqrGlCLCBRpGEh1EpLaPYM/view?usp=drive_link",
  "Halloween 7": "https://drive.google.com/file/d/1DHw9eGrjlTXogscCDZFCfOfab951KL0Q/view?usp=drive_link",
  "Halloween Resurrection": "https://drive.google.com/file/d/10Dl77pstp-05sbrnKQGlSPvt5yaVXh4k/view?usp=drive_link",
  "Halloween 2007": "https://drive.google.com/file/d/1RTbD5uzFxZIcfrX5nkGRIq0biquf40bz/view?usp=drive_link",
  "Halloween 2 2009": "https://drive.google.com/file/d/1UQWZPTAEVeiDBtY-lxG9RF6v5B_mizcp/view?usp=drive_link",
  "Hamilton": "https://drive.google.com/file/d/1c47Nko9vdJfe-KKF4nkpd-U-aMT_ZaQe/view?usp=sharing",
  "How to Train Your Dragon": "https://drive.google.com/file/d/1_1kjmaNVAhaccTH3mCV5FfcML3MTiT0E/view?usp=drive_link",
  "How to Train Your Dragon 2": "https://drive.google.com/file/d/1lygHQMhfWWBjlp1mzSaOI5kDsbBq6Ibn/view?usp=sharing",
  "How to Train Your Dragon: The Hidden World": "https://drive.google.com/file/d/1cS4L5FYnWergTViVgJJpKbMIIi8sju4P/view?usp=sharing",
  "Head Over Heels": "https://drive.google.com/file/d/10N4s7Roujs0L7wRWNKltdWOPcoC29hiv/view?usp=sharing",
  "Harry Potter and the Sorcerer's Stone": "https://drive.google.com/file/d/1bJMKhvzwuVfAYECLheyA_h38T9oYvkgX/view?usp=drive_link",
  "Harry Potter and the Chamber of Secrets": "https://drive.google.com/file/d/1AC6j5pNVDl6fcvdT3e3hsAUkkBU-o3xD/view?usp=drive_link",
  "Harry Potter and the Prisoner of Azkaban": "https://drive.google.com/file/d/1Zu15ykGtc1xxKIKfAeUV_L1vAbCt--zO/view?usp=drive_link",
  "Harry Potter and the Goblet of Fire": "https://drive.google.com/file/d/1yYxqmSv99zFBsJkT0cZYd4C4PTNC9bUU/view?usp=drive_link",
  "Harry Potter and the Order of the Phoenix": "https://drive.google.com/file/d/1eVK_s8Sp-Gvv1J65ocyLbwyqC7vkuoFK/view?usp=drive_link",
  "Harry Potter and the Half Blood Prince": "https://drive.google.com/file/d/1QfAnvJtU3oR7IV2CrN2qRx4vFThjbbe1/view?usp=drive_link",
  "Harry Potter and the Deathly Hallows": "https://drive.google.com/file/d/17UlhT2qVX10O8AksEEdWuaUqoVF78-oH/view?usp=drive_link",
  "High School Musical": "https://drive.google.com/file/d/16jXkeJny6L8MrC_7issz4AtANAzNDJqw/view?usp=drive_link",
  "High School Musical 2": "https://drive.google.com/file/d/1iE1foAQrNAMJJg3aOd37GECWBkXmAEi7/view?usp=share_lin",
  "High School Musical 3": "https://drive.google.com/file/d/1aGq7saEhWkyACQlOmGIAmylSTeEOL864/view?usp=share_link",
  "Hairspray": "https://drive.google.com/file/d/12X1rfnx0NrQUAhDRLRQxKdaqvAi_LqJa/view?usp=sharing",
  "How the Grinch Stole Christmas": "https://drive.google.com/file/d/1_z5TUQlNH-IWdeFo_jDZDKsuVi32VdRs/view?usp=drive_link",
  "Incredibles": "https://drive.google.com/file/d/1XZrELbZbBqHShrCiPr4I4_pmOeT_gvwY/view?authuser=0&usp=share_link",
  "Incredibles 2": "https://drive.google.com/file/d/1XZ0pSe4bccOpJeF_VkXhkOhxQ3Tzp8RB/view",
  "I Know What You Did Last Summer": "https://drive.google.com/file/d/1sSPtR3lcvTcjtDHvv3sOHw8qHbuaeQY1/view?usp=sharing",
  "Indiana Jones and the Dial of Destiny": "https://drive.google.com/file/d/1BuNmXFmhFBoSKvcnbi5W1_hQkVLTrzwu/view?usp=sharing",
  "Inside Out": "https://drive.google.com/file/d/1BEPGPg_iR7L5QFJ91SizjlA6khwj6j1e/view?usp=sharing",
  "Inside Out 2": "https://drive.google.com/file/d/148ae2JtLzIZwy-AKjtRgLZPNf3vEmQOE/view?usp=drive_link",
  "The Instigators": "https://drive.google.com/file/d/1LPBpsJpE56zpdSZUi8f6tEkHPzaMceYo/view?usp=drive_link",
  "Thirteen": "https://drive.google.com/file/d/10HMzcDDav-A9xTydLioxLEfcou7SICYL/view?usp=sharing",
  "Jurassic Park": "https://drive.google.com/file/d/1QGXy2lJU4B0z4s7zPSOLizN8jMHfnZQm/view",
  "Joker": "https://drive.google.com/file/d/1czY5u0zA3TPQh97OFth_1GkaK9nUo-Lq/view?usp=drive_link",
  "Joker: Folie à Deux": "https://drive.google.com/file/d/1wiipkIcZ8r4itPij4w7CpOvC6uz-2wCS/view?usp=drive_link",
  "Jingle All The Way": "https://drive.google.com/file/d/1gdQba6i5IcBe7_a4eyU75cuAkbyJEpt4/view?usp=share_link",
  "John Wick": "https://drive.google.com/file/d/1o-u405CtHzkRFAjDRxnlwIV1MKzmpQYa/view",
  "Jumanji": "https://drive.google.com/file/d/1tXnq5Vy82ADqguaPVxH586h3IR5x6vEZ/view?usp=drive_link",
  "Jumanji: Welcome to the Jungle": "https://drive.google.com/file/d/1KownBUZELkJDdp-Rbg8Z4YI7n1msEWbD/view?usp=drive_link",
  "Jumanji: The Next Level": "https://drive.google.com/file/d/1aM4O7Zp59daNOwMVW7jvHYUCLEwAXjI_/view?usp=drive_link",
  "K pop demon hunters": "https://drive.google.com/file/d/1GEdn_mwI54q0CVU2A-iahOHkFgk-mys3/view?usp=sharing",
  "Kill Bill Volume 1": "https://drive.google.com/file/d/1O7IPP73pLpqj6qH4mfqjDhwNbeDMSU7N/view?usp=drive_link",
  "Kill Bill Volume 2": "https://drive.google.com/file/d/1p5DfNhB87k8bE-OQi7ELONmPkIhJIjC-/view?usp=sharing",
  "Kung Fu Panda": "https://drive.google.com/file/d/1cPYsXfP2YqdtUNnqXg3ycANRQQOuVOmR/view",
  "Kung Fu Panda 2": "https://drive.google.com/file/d/19Iz7pU-A9RUMHe6q1I9faYi02ht5MwbT/view",
  "Kung Fu Panda 3": "https://drive.google.com/file/d/1lfSnf9FQoB1xyeDJxEEh5JSG4ocnmqgx/view",
  "Kung Fu Panda 4": "https://drive.google.com/file/d/19e3HaItYsMHMCjHE0HD78-GsG1rbftJl/view?usp=sharing",
  "Karate Kid": "https://drive.google.com/file/d/1tMJAooF8bG9ghav9CU4GPYF3t07ySMXL/view?usp=sharing",
  "Labyrinth": "https://drive.google.com/file/d/13TgTB15A99LLWI_ROcci18FT8ijuq8RC/view?usp=drivesdk",
  "Madagascar": "https://drive.google.com/file/d/1TvrE3-T2tdfFhmEdhG_-NJlGNMnhHt2J/view",
  "Madagascar 2": "https://drive.google.com/file/d/1uNRfbrFF8al6BtxKkXWhuq-DeMVd9NZn/view?usp=share_link",
  "Madagascar 3": "https://drive.google.com/file/d/1W4aM_WbjjxTlE_f5zcKPYZ5pNOym_W8K/view?usp=share_link",
  "Megamind": "https://drive.google.com/file/d/1Xg-DLA7N4hHN38uQ4IxReyxMeC10pAJT/view",
  "Miraculous New York": "https://drive.google.com/file/d/1jTfxqP7BrcbIv5SVAxHP7FFIdt8A51ZJ/view?usp=share_link",
  "Miraculous Shanghai": "https://drive.google.com/file/d/1jTfxqP7BrcbIv5SVAxHP7FFIdt8A51ZJ/view?usp=sharing",
  "Minions": "https://drive.google.com/file/d/1Wz1VPwDHWA3t8n54e-YpRM18ad1mQuSG/view?usp=share_link",
  "Minions: Rise of Gru": "https://drive.google.com/file/d/1lrJNkBON3H_5n8lF3WKCaUT6AUl9qbh4/view",
  "M3GAN": "https://drive.google.com/file/d/1MMl1EYr_OYdc9R-va2IIdPUmkqcj1UpR/view?usp=drive_link",
  "Boo! A Madea Halloween": "https://drive.google.com/file/d/1vBDYkMbS1WR0E5tOj0Tdou9S6HJ5Nb5w/view?usp=sharing",
  "Boo 2! A Medea Halloween": "https://drive.google.com/file/d/1p8PGU6RQya7wIRi5no4pPNOVRaBbnfwR/view?usp=sharing",
  "Maleficent": "https://drive.google.com/file/d/1yx66GkjBaCwjcMNoovV8w9yPNlZ7Q4Gu/view?usp=drive_link",
  "Mortal Kombat": "https://drive.google.com/file/d/1temXH9CFHCd7gjIsu8TMCFiqxMy8jXfj/view?usp=drive_link",
  "Mean Girls": "https://drive.google.com/file/d/1Hab49OuPK37MngOtQolLsVIzJ4AK9cNA/view?usp=sharing",
  "Monsters Inc": "https://drive.google.com/file/d/1lmlVArBa1cDynHvvDOddrMnCPvYaFVeK/view?usp=drive_link",
  "The Matrix": "https://drive.google.com/file/d/1qUy2Uk4nAGj72Ev81g67tx-snjKA-6Ne/view?usp=drive_link",
  "Moana": "https://drive.google.com/file/d/1Zkep5HZHk6daQhYjAN5Y9fBGy-K9dCu3/view?usp=drive_link",
  "Moana 2": "https://drive.google.com/file/d/1khAaDGsMt8pAGqtIPJERCqM_PgpiLShO/view?usp=drive_link",
  "Mufasa": "https://drive.google.com/file/d/1uQXNlwz-_1PwGdnJqTGUswBhJWgH8zMP/view?usp=drive_link",
  "Mulan": "https://drive.google.com/file/d/1ye-qQ6ZmBW98Xab4sjDJw1oxmUw_piBz/view?usp=sharing",
  "A Minecraft Movie": "https://drive.google.com/file/d/1Lk4wglli3RBp9S9_BLq9jf1TSeFUHV6h/view?usp=drive_link",
  "Norbit": "https://drive.google.com/file/d/1PUIzjrlfRen4M7CqwIcmVdABNBpMWt5s/view",
  "Pacific Rim": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/pacific-rim?authuser=0",
  "Pacific Rim Uprising": "https://drive.google.com/file/d/1rZZBiG6H7Q2Fznd552IxwQrIu0-X43zq/view?usp=sharing",
  "Puss in Boots: The Last Wish": "https://drive.google.com/file/d/1SxMLkaBMyPSuruaAmGWoA7AKB4FV9j3J/view?usp=sharing",
  "Power Rangers: The Movie": "https://drive.google.com/file/d/1e-f3lzrTrRV3iVT7Ft-KLSd6fHbyUT2i/view",
  "Peanuts": "https://drive.google.com/file/d/16Ze08q_XKmANPNYreDVZnEbZEZTSLwOa/view?usp=share_link",
  "Polar Express": "https://drive.google.com/file/d/19KYYKqlEQyEuUTUQv32U53WoIDvKTRrx/view?usp=sharing",
  "Paw Patrol: The Mighty Movie": "https://drive.google.com/file/d/13PKSmF1dnXkByra1B5NLarzB_ux4cU0T/view?usp=drive_link",
  "Power Rangers": "https://drive.google.com/file/d/1bAS1zgiXsYJVXzhra9Fg2PHWBbVDU8lJ/view?usp=sharing",
  "Piece By Piece": "https://drive.google.com/file/d/1VFcUmw2ezWybQqevoY8jh3F50yWkxwzQ/view?usp=drive_link",
  "Pixels": "https://drive.google.com/file/d/1Wpvc4eawdHc3DjkVVop959tYmJL6m3J2/view?usp=drive_link",
  "Rise of the Planet of the Apes": "https://drive.google.com/file/d/1gfhsOi21mgw9MPdSo6ttTMFJbhNKuwjn/view?usp=drive_link",
  "Ready Player One": "https://drive.google.com/file/d/1vCPMrNGFL3Kyf1J4qaySzKnACtg8eAqj/view?usp=drivesdk",
  "Rio": "https://drive.google.com/file/d/1DIHKkPm7JVwOWWgM5RvYgOhAbFXWOAhf/view?usp=share_link",
  "Rio 2": "https://drive.google.com/file/d/12oiUUNl2_I7l1GsXLD74FA0wJlrRX7v_/view?usp=share_link",
  "Real Steel": "https://drive.google.com/file/d/1zamnVJgx2cGGc4r2w9jWiEqRIG9WJREE/view",
  "Ratatouille": "https://drive.google.com/file/d/1kjVDdXtZ3-O0SndMHeIwMXe4jNZJ4w2C/view?usp=sharing",
  "Ron's Gone Wrong": "https://drive.google.com/file/d/1nKl-oBgmnWygnF7xm6CfSWikp22ElVZY/view?usp=share_link",
  "Rambo 3": "https://drive.google.com/file/d/1KDIkm6VSTb_QrvSb8Gvbus8z-L3BGySI/view?usp=sharing",
  "Rugrats The Movie": "https://drive.google.com/file/d/157WJal3P65gdyFlDbP4DcRfNku-Oursg/view",
  "Rugrats In Paris": "https://drive.google.com/file/d/1w3PdNgN0AXDmG1CYRv7v0kMYrC1Ywu_0/view",
  "Romeo + Juliet": "https://drive.google.com/file/d/12_qQEuH75vHIqFjIwmDlawqQmav5RG-u/view?usp=drive_link",
  "Road to El Dorado": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/road-to-el-dorado?authuser=0",
  "Rush Hour": "https://drive.google.com/file/d/1ZcBKqjCxKjyddbVmb8sdOtCo-14v6fTp/view?usp=drive_link",
  "Rush Hour 2": "https://drive.google.com/file/d/1mnNpYvlG_QNVxpq8LniD4hOPLPinnBEP/view?usp=sharing",
  "Rush Hour 3": "https://drive.google.com/file/d/1fIOuM1hV1Ga0O6eQrhvozLNc35Rw-XB8/view?usp=sharing",
  "Saw": "https://drive.google.com/file/d/1nZn3QfKiiZgg4nx3GRA4-K6obuJLlepm/view?usp=drive_link",
  "Saw 2": "https://drive.google.com/file/d/1eQLt5qFXYBjdvN05Jryfkc0MUF6eLZfS/view?usp=drive_link",
  "Saw 3": "https://drive.google.com/file/d/1afqsupX8WtCzEt3AbeKe_Ffwfb4oXzsa/view?usp=drive_link",
  "Saw 4": "https://drive.google.com/file/d/1XmKqBrU4I1QqPnKG5WGpVImeTFvBjy0n/view?usp=drive_link",
  "Saw 5": "https://drive.google.com/file/d/1Rng7E07HcEPZmWvxYHk2gnrhArp_0MsS/view?usp=drive_link",
  "Saw 6": "https://drive.google.com/file/d/1v_fqql_iAIszlP5qG5735UX8NVGXXFud/view?usp=drive_link",
  "Saw 7": "https://drive.google.com/file/d/1uMSvmCNTmuuY_imm9J8ZvipQW8rWMcCJ/view?usp=drive_li",
  "Scrooged": "https://drive.google.com/file/d/1zmDJ-0X5qV2niOZe7ZsL_sPk6w7XvDnr/view?usp=drivesdk",
  "Scream": "https://drive.google.com/file/d/14UKIE2jtMo0qFPbomlXVKsKA5l81W4OE/view?usp=share_link",
  "Scream 2": "https://drive.google.com/file/d/1XXmiwcrUSMi5rn90xr5hnBK6La8hBkhz/view?usp=share_link",
  "Scream 3": "https://drive.google.com/file/d/1O1mkNEfq98w2Zrxyg6XLCfJI_bmfwWp_/view?usp=drive_link",
  "Scream 4": "https://drive.google.com/file/d/1t4kNJPFCytvx2ktdw5n6xBOtRNnBm5RJ/view?usp=share_link",
  "Scream 5": "https://drive.google.com/file/d/152-KeFdBMBscGESWVWLuDS-YUf8VsRCd/view?usp=share_li",
  "Scream 6": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/scream-6?authuser=0",
  "Shark Tale": "https://drive.google.com/file/d/1tqtj-_jOe_a1DtU3ekZSf5n8NEtHT8hn/view?usp=share_link",
  "Space Jam": "https://drive.google.com/file/d/1QK9RHd2T-ijthIL7A6NQvRztPkTx8NtN/view?usp=sharing",
  "Space Jam: A New Legacy": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/space-jam-a-new-legacy?authuser=0",
  "Sonic": "https://drive.google.com/file/d/1h1hi-3Hn1awll6u51WQnGjkHqm3uJejF/view",
  "Sonic 2": "https://drive.google.com/file/d/1cXe1a5ueZU9U_QZBU1-XpgNK0s6wi4o6/view",
  "Sonic 3": "https://drive.google.com/file/d/1Pvg1OeuLicH_k3H1TOhomgJSmTugmm0d/view?usp=drive_link",
  "Spider-Man: Homecoming": "https://drive.google.com/file/d/1jGHx1i3EqHKmQmE42APmxUk4bYHrINQ_/view",
  "Spider-Man: Far From Home": "https://drive.google.com/file/d/1vPNUTkubVVmguVfwstRQm5xgbkRRii6z/view",
  "Spider-Man: No Way Home": "https://drive.google.com/file/d/1mUF4PcT0_ZKofV0KHHdjxgTQdhF2BliQ/view",
  "Spider-Man: Into the Spider-verse": "https://drive.google.com/file/d/1V3Bq0lrDQUxJay5DDs3gK69ZvRNb1j2u/view?usp=share_link",
  "Spider-Man Across The Spider-Verse": "https://drive.google.com/file/d/1Sd1l_LhKRp_2OE5gRJJyPubnZjJccLgQ/view?usp=sharing",
  "Spider-Man": "https://drive.google.com/file/d/1sqWGrmbGc5lBmoFbtfMSIaqb60eXppvF/view?usp=share_link",
  "Spider-Man 2": "https://drive.google.com/file/d/1yV7ZmEkfOVOLdV51wN6vSeDf3_tQqBvf/view?usp=share_link",
  "Spider-Man 3": "https://drive.google.com/file/d/1ExTfRPC3YGmCSg8W2uFSYkUMw7a1vcTR/view?usp=share_link",
  "Shazam": "https://drive.google.com/file/d/111DMVHuhGLLFunQ1ixi_OG8ui0ckXbfU/view?usp=share_link",
  "Shazam: Fury of the Gods": "https://drive.google.com/file/d/1LC17KNt1pxG1zJ43CwIBNGXaCN3cmLPc/view?usp=share_link",
  "Amazing Spider-Man": "https://drive.google.com/file/d/1Xf8xZcY3kneGFln8NPsQMt7CLtmGhEeD/view?usp=drive_link",
  "Amazing Spider-Man 2": "https://drive.google.com/file/d/1hnYa-Pkxqu6Qhhp56QXE34Rnctia_3yw/view?usp=drive_link",
  "Superman (2025)": "https://drive.google.com/file/d/1A61oIlDB8zy0cgj2tJdquKVpaJzl26mr/view?usp=sharing",
  "Suicide Squad": "https://drive.google.com/file/d/1m2m6kudeN5pivaeCWfMR88xXEyZg8nFK/view?usp=sharing",
  "The Suicide Squad": "https://drive.google.com/file/d/11nKqV7QKkATlvO7pt8eHlfS32rSHeOVZ/view?usp=sharing",
  "Star Wars: The Phantom Menace": "https://drive.google.com/file/d/1R-AxDZKs_TI09vQm_ZDKaeAViZjssWpC/view?usp=drivesdk",
  "Star Wars: Attack of the Clones": "https://drive.google.com/file/d/1u0ZRN7s8rgAMYtvnGf3zTjpM7Fu6TmW_/view?usp=drive_link",
  "Star Wars: Revenge of the Sith": "https://drive.google.com/file/d/1lEszWnr2BinTfzBGqtoDV1W9wMIlTQtb/view?usp=drive_link",
  "Star Wars: A New Hope": "https://drive.google.com/file/d/1nDgCNAuFgSI6fDKbRZFkDhzViib1ixYS/view?usp=drive_link",
  "Star Wars: The Last Jedi": "https://drive.google.com/file/d/1vCdep3QXu8GE9IaNUdVmCGLiG24kFrWb/view?usp=drive_link",
  "Star Wars: The Empire Strikes Back": "https://drive.google.com/file/d/1q0Jof59Il_So2z5Q38ANn55qB2GCpOx3/view?usp=drive_link",
  "Star Wars: The Force Awakens": "https://drive.google.com/file/d/1D-T-C4PNPbZ61wiHqXgQlQqYy_NTcsKa/view?usp=drive_link",
  "Star Wars: The Rise of Skywalker": "https://drive.google.com/file/d/1viDV-Gu6yGHOpyaDefPH3Id9fXSHuTsi/view?usp=drive_link",
  "Solo: A Star Wars Story": "https://drive.google.com/file/d/1cVMCqyg7byeajsDkn4cyHQe7SSLfxVPL/view?usp=drive_link",
  "Star Wars: The Clone Wars": "https://drive.google.com/file/d/16dO2t6nMYzRFTKGBVByMPYtru6kwix7H/view?usp=drive_link",
  "Strays": "https://drive.google.com/file/d/1mwatNbn0A7PeIm_alMZGYobXbsNIgBlo/view?usp=sharing",
  "Sing": "https://drive.google.com/file/d/1bRSwv4_BuhY_StvUSf1TXE3QxC9R9ADA/view",
  "Sing 2": "https://drive.google.com/file/d/1uDLZSi8eF0AMJjciagelGOQSJVDshSDU/view",
  "Snitch": "https://drive.google.com/file/d/17hMZl5qq3Khflm_xUYZW9b8nGCJ6OBfA/view?usp=sharing",
  "Shrek": "https://drive.google.com/file/d/1ps_r1YV8y5h93_mUu4OFlPVVkPzT0Rui/view",
  "Shrek 2": "https://drive.google.com/file/d/1NoWXqvxNnXPiBj0kLY1lINF00Gg17mme/view?usp=drive_link",
  "Shrek 3": "https://drive.google.com/file/d/1qhxQw4uC6aO1KN0UZrybu1YY1vdtBwmM/view?usp=drive_link",
  "Shrek Forever After": "https://drive.google.com/file/d/1xN-pzN1CePUsWHTmd9o--cOA-X_gqzQg/view?usp=drive_link",
  "Scary Movie": "https://drive.google.com/file/d/1-61Fls8_MDTVq3r5dHP58joVRiUloxZQ/view?usp=drive_link",
  "Scary Movie 2": "https://drive.google.com/file/d/1Jmeyjhlpg6A-W-XJPoqC8uhtWztuQe-F/view?usp=drive_link",
  "Scary Movie 3": "https://drive.google.com/file/d/1O1mkNEfq98w2Zrxyg6XLCfJI_bmfwWp_/view?usp=drive_link",
  "Scary Movie 4": "https://drive.google.com/file/d/1pgH5VfJEi5NRVEtp2y_vZMSOk_rh3Har/view?usp=drive_link",
  "Scary Movie 5": "https://drive.google.com/file/d/1nnGh4CzlDg_ymz9YeDwl6L3ZXroIKtRu/view?usp=sharing",
  "Sleepy Hollow": "https://drive.google.com/file/d/18gseXON5RP2ipsWcd0XGZH9k4TyaeYYR/view?usp=drive_link",
  "Smile": "https://drive.google.com/file/d/1-uZq4Am62uCfNJoudwKp6ffq9T0o_LKF/view?usp=drive_link",
  "Smile 2": "https://drive.google.com/file/d/1VUL8POnA90Py_wWlhPwUq8e4J6Z1lTJ9/view?usp=drive_link",
  "Scarface": "https://drive.google.com/file/d/1yC6lNaMy_WUIK3eKkKoRSEU0Y-cSJBnV/view?usp=drive_link",
  "The Lion King": "https://drive.google.com/file/d/1GrJxp4D9XrmYBG_bqRgp1UvQaapyjoV7/view",
  "The Lion King II: Simba’s Pride": "https://drive.google.com/file/d/1-sT4cdDqG6tt4wI0ba7Z3FhDoX8ded8L/view",
  "The Lego Batman Movie": "https://drive.google.com/file/d/1Xn4F4GNvfKOljko2ZE_JUQcBWIHhO0ql/view",
  "The Lego Movie": "https://drive.google.com/file/d/1j2kFu1apjVp0E2_xojdiqASlQOc8RBit/view",
  "The Lego Movie Part 2": "https://drive.google.com/file/d/1_sb4Ogn-0xQX3Znf21COpLMrfs_x6Nuv/view",
  "The Little Rascals": "https://drive.google.com/file/d/1eiY3r9KqM3Dmjtq38eRtR_eJFSGeciPz/view",
  "The Lorax": "https://drive.google.com/file/d/1g6ZVlbeJ05SY5jleCqn_PMUMzevqPX6Y/view?usp=sharing",
  "The Sandlot": "https://drive.google.com/file/d/1G9qRpMiBq5HD-vqKQs9sq8csZCFccaiD/view",
  "The Brave Little Toaster": "https://drive.google.com/file/d/1qZxoOGQTxqwlJtOQbwN8jeyD_yVvX7yc/view?usp=share_link",
  "The Chronicles of Narnia": "https://drive.google.com/file/d/14TYyfl0ogVnDyw_yKCrU_jKGPIDBM3Nu/view?usp=share_link",
  "Prince Caspian": "https://drive.google.com/file/d/1DxOEqY1EzxcJYSNk2s6xXLf2SSP-hTRI/view?usp=share_link",
  "The Voyage of the Dawn Treader": "https://drive.google.com/file/d/12_UK0B8umPhjw5c5WOge3PtcGoDB9Uk2/view?usp=share_lin",
  "The Princess Bride": "https://drive.google.com/file/d/1YnPym55TCYUgdEe65MHELL13ygweFutT/view?usp=drivesdk",
  "The Proud Family Movie": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/the-proud-family-movie?authuser=0",
  "The Lego Ninjago Movie": "https://drive.google.com/file/d/1wQIj-ZVsTxgTktceYFgyFei_XX-eXAt-/view?usp=sharing",
  "The Super Mario Bros. Movie": "https://drive.google.com/file/d/1q2pk3lo5VIDWKQq2lCh_UTC_V9Zkv-_X/view?usp=drive_link",
  "The Wizard of Oz": "https://drive.google.com/file/d/1ZfNxrVWB0U1Nwsrc03i5v9vGJtMJ9Ts3/view?usp=drivesdk",
  "Return to Oz": "https://drive.google.com/file/d/1qINcGAx8SUBfoh3O-HeVLetY_rSVueAG/view?usp=drivesdk",
  "Teen Titans: Judas Contract": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/teen-titans-the-judas-contract?authuser=0",
  "Teen Titans: Trouble in Tokyo": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/teen-titans-trouble-in-tokyo?authuser=0",
  "Transformers": "https://drive.google.com/file/d/17FH0E-XliQ0VAWNnxrwkvhUrCCGLKx2A/view?usp=share_link",
  "Revenge of The Fallen": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/transformers-revenge-of-the-fallen?authuser=0",
  "Dark of The Moon": "https://drive.google.com/file/d/19dfiTEEqIVE9cxVBsyNVoG5c4UebhS0F/view?usp=share_link",
  "Age of Extinction": "https://drive.google.com/file/d/1evgnLc_0TRlHQ8_tcMcZYaYY-2_RmKWZ/view?usp=share_link",
  "The Last Knight": "https://drive.google.com/file/d/1b9ZHT2vDIp-JJ9JD0PWbEbyU1bDZMcPl/view?usp=share_link",
  "Bumblebee": "https://drive.google.com/file/d/1wqi9Wk--koq0SqRkoVZWXLVJBtABkjPy/view?usp=share_link",
  "Rise of The Beasts": "https://drive.google.com/file/d/1Xunn1qXhQ1jvB5VXYiv0LShGAvD74u2Q/view?usp=sharing",
  "Tron": "https://drive.google.com/file/d/1hbhWcI11gA5EcXAxXGJkIjzq7VQIpZGp/view?usp=drivesdk",
  "Teenage Mutant Ninja Turtles": "https://drive.google.com/file/d/1ivJXBaVGvN_HQJf-h46ko2DjyHHBZMH1/view",
  "Secret of The Ooze": "https://drive.google.com/file/d/1Bp9ioxFqOCfmEbQM90cbLcFAn9bPysDu/view",
  "TMNT 3": "https://drive.google.com/file/d/1gdIpjtTCHV_a8p9KPQaQg1ljIcanpu5S/view",
  "Turning Red": "https://drive.google.com/file/d/1joF2I_zdjepCD9ukmjV672HTICUfp4tO/view",
  "TMNT 2014": "https://drive.google.com/file/d/1nfyJg41IDD_zRmv3i64MUSpPuCPTq7gb/view?usp=sharing",
  "Out of The Shadows": "https://drive.google.com/file/d/1fWvuZyyF8dWKn9y60awRgwTxKAQd11cl/view?usp=sharing",
  "Mutant Mayhem": "https://drive.google.com/file/d/1IZNQlKBJi5HwRJDokQ-YuxfteFKgLZI5/view",
  "TMNT": "https://drive.google.com/file/d/18iqYAOVbRHOT7jzJ3sqlyxi8RS5AH5sM/view?usp=sharing",
  "The Good Dinosaur": "https://drive.google.com/file/d/1vELzmz9u6vQ18YtMipK9nSWJhZLP6KaH/view?usp=sharing",
  "The Little Mermaid": "https://drive.google.com/file/d/1GM7QyJzFwEKM2fM42SWb7oIRN2UPUzqM/view?usp=sharing",
  "The Brady Bunch Movie": "https://drive.google.com/file/d/18i5j4gguKnfjNXVcfPKLz3GbxaiWbhrh/view?usp=drive_link",
  "A Very Brady Sequel": "https://drive.google.com/file/d/139xwpHkb9tF64bSc0PnKZMBGtdCHh7pW/view?usp=drive_link",
  "The Mask": "https://drive.google.com/file/d/13IzLS6dOFDxCk_mNWpttFncqs1hQoJ3L/view?usp=sharing",
  "The Addams Family": "https://drive.google.com/file/d/19ZYLs_076nTJtl7bEUtkwpfbwwj-GevJ/view?usp=sharing",
  "The Little Mermaid 2023": "https://drive.google.com/file/d/1sFYkkRX85JK-a2LRl8_QmZPhYkYIn6KG/view",
  "The Smurfs": "https://drive.google.com/file/d/1gbp16Rw9fcysqsoY5vAxZqgXwNzKDfr2/view?usp=sharing",
  "The Smurfs 2": "https://drive.google.com/file/d/1FYgtU8rAKF32RjDRgYqODXzOHV0mQuBy/view?usp=share_link",
  "The Flash": "https://drive.google.com/file/d/1ApUHMkZM-j3vM-rSG-kvjk3KuvJNAsXp/view?usp=sharing",
  "The Book of Life": "https://drive.google.com/file/d/1_MkoFWTqhvJM4YNqGFzSabwKSSL4fa55/view?usp=drive_link",
  "The Nightmare Before Christmas": "https://drive.google.com/file/d/1BPYV-xYt77pQYztFM14VHk3wBZZ_l0ng/view?usp=sharing",
  "Twilight": "https://drive.google.com/file/d/1YEIurV6IBGg7IYqTE9EX2vHLUQeEfBjH/view?usp=sharing",
  "The Twilight Saga: Eclipse": "https://drive.google.com/file/d/1l3n45XIBKJuV8Osp7V30X3Ki4QgAa4Cn/view?usp=drive_link",
  "New Moon": "https://drive.google.com/file/d/1LTDkhMpQLpkNdy6KVU81H-Y_J4lQ3PHV/view?usp=drive_link",
  "Breaking Dawn Part 1": "https://drive.google.com/file/d/1GTUALkIJ4mkxae00sdbQdGUhUl4i8lGm/view?usp=drive_link",
  "Breaking Dawn Part 2": "https://drive.google.com/file/d/12J1e35T-HQtLoTvfs70-TlZ4oJsXsxvX/view?usp=drive_link",
  "The House With a Clock in Its Walls": "https://drive.google.com/file/d/18jZoJEwkjPPDp3OPD-fevwoyl_1g6EpO/view?usp=drive_link",
  "The Menu": "https://drive.google.com/file/d/14Audx3RqZPMTyLzErPzkKuCQPVWhTC0y/view?usp=sharing",
  "The Swan Princess": "https://sites.google.com/view/ttbr-11-777-ggbht/moves/swan-princess?authuser=0",
  "The Princess and The Frog": "https://drive.google.com/file/d/1PIQExpRvAPANHRDAZ-On7ld9je2O-5He/view?usp=sharing",
  "Trolls Band Together": "https://drive.google.com/file/d/1XRVLJkHTb7yOjW2daDKL1LQq_ySsRghU/view?usp=drive_link",
  "The Greatest Showman": "https://drive.google.com/file/d/1ErElLX4tetXsqWfpivPg3JlEht4ERibn/view?usp=drive_link",
  "Terrifier": "https://drive.google.com/file/d/18N4_ou-sji02HD3dOFNP0aDqCBleLr7G/view?usp=drive_link",
  "Terrifier 2": "https://drive.google.com/file/d/1i68ih2XgYHdjDTqR_pfmXuFut_LuCtZY/view?usp=sharing",
  "Terrifier 3": "https://drive.google.com/file/d/1C0yGUsqW5IT81q8PAebnlw0Ha6oHWYV4/view?usp=drive_link",
  "Tangled": "https://drive.google.com/file/d/1eirKJt3ulfEusRJ6OM0jwpJ_YbL8iExC/view?usp=sharing",
  "Transformers 1": "https://drive.google.com/file/d/10cwJT2ssiHVBeRWMdEVHKt0bhk8PVOHY/view?usp=drive_link",
  "The Wild Robot": "https://drive.google.com/file/d/1SRZU-WaeYNHMvHNEwl3uAIuMSOJ4R1jY/view?usp=drive_link",
  "Us": "https://drive.google.com/file/d/1ij57VuW6Bjxq713L53oKgAIx4iR8yoVB/view?usp=sharing",
  "Venom": "https://drive.google.com/file/d/1iRN197XeJCQnZGza599ZTXsayEG1mdRB/view",
  "Let There Be Carnage": "https://drive.google.com/file/d/1N6kL0SF4qR6wFpwfGIZUZjFnz3lQDGGz/view?usp=sharing",
  "Venom: The Last Dance": "https://drive.google.com/file/d/1hASiHRDz9oyG-NSHEzLNLPFeAMa_HuoH/view?usp=drive_link",
  "White Chicks": "https://drive.google.com/file/d/1IniRDbSyVeGuGIadQ_rX9RL8AJczmm2S/view?usp=drive_link",
  "Wicked": "https://drive.google.com/file/d/1fG4xZ8p6mptdbf-Vji5rhlIoXeKG6Dcd/view?usp=drive_link",
  "Wicked For Good": "https://drive.google.com/file/d/1nuTy_XH_23jidTMbwRZJfR5ZQl3vzi3z/view?usp=sharing",
  "Who Framed Roger Rabbit": "https://drive.google.com/file/d/13qCLa-UbWgLKDkm5EYs7y3-n5NVx7-73/view",
  "Wreck-It-Ralph": "https://drive.google.com/file/d/11NQ1_ecO2FTIhofVPIfakshgSBnR6ngC/view",
  "Wreck-It-Ralph Breaks The Internet": "https://drive.google.com/file/d/1MQMWT5mYBF07GXiqgzAU8h9BcFe0phu9/view",
  "White Men Can’t Jump": "https://drive.google.com/file/d/1MXghG0Dnn9XJ9iSGE6-bIuM7vysIxBfy/view?usp=drive_link",
  "White Men Can’t Jump (2023)": "https://drive.google.com/file/d/1-WrSZaYE3Sq_bHifzyd4UJP7tc6Ea0Ur/view?usp=drive_link",
  "Wish": "https://drive.google.com/file/d/1KOmgE1jMV0jT2QkWFFd3ieEzwf4GbVOw/view?usp=drive_link",
  "West Side Story": "https://drive.google.com/file/d/1CBGr82HWTP2XM-HJPURXFGV1uqE5-ip-/view?usp=drive_link",
  "West Side Story (2021)": "https://drive.google.com/file/d/1XCfKDI8cKvYQO2UGFOKBe5qlmcL8Vsry/view?usp=drive_link",
  "Willy Wonka & The Chocolate Factory": "https://drive.google.com/file/d/1oeD_wjeRQck_3uRIOw9ZXIxG5PuUIPVD/view?usp=drive_link",
  "X-Men": "https://drive.google.com/file/d/1BIJIiG8fdpyudl-1vXHIU3TBb3XMXJaa/view",
  "X2": "https://drive.google.com/file/d/16fA19e1MhAZaUaosRHey_c1VAZoM1iB8/view",
  "X-Men: The Last Stand": "https://drive.google.com/file/d/176dVR22sSEaJMY5TfITCW9TIC2fNYBMm/view",
  "Interstellar": "https://drive.google.com/file/d/14VeNSqVtt5gcibZOfjPcjkBoasPrpiEG/view",
  "Star Wars": "https://drive.google.com/drive/folders/16dO2t6nMYzRFTKGBVByMPYtru6kwix7H",
  "Forrest Gump": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Pulp Fiction": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Inception": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Fight Club": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Gladiator II": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Oppenheimer": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Avatar": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Avatar: The Way of Water": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Top Gun: Maverick": "https://drive.google.com/file/d/1ehi9tidOYHb1RMldxtBw6-L3UhyEKVm9/view",
  "Zootopia 2": "https://drive.google.com/file/d/1-PX9OZ8C3YrvjFtGhnH-YRO8kz75chAW/view?usp=sharing",
  "Zapped": "https://drive.google.com/file/d/1gO0OtMfAoVUaZGxX825aH48OySgHYd5n/view?usp=sharing",

  // TV Shows
  "IT Welcome to Derry": "https://drive.google.com/drive/folders/1UABFLoCQG6DEdQkJwbbUPqYulGLsSiw2?usp=drive_link",
  "IT Welcome to Derry S1": "https://drive.google.com/drive/folders/13dLvT0_1TkcRmVmF6tZlm80xqeoWhxZp?usp=drive_link",
  "IT Welcome to Derry S2": "https://drive.google.com/drive/folders/1gAtljQ6SnEWUS8HXW-y5jtbcKILcUnFU?usp=drive_link",
  "Adventure Time": "https://drive.google.com/drive/folders/1OwoKydzUQUUp6n-Nh7CCAQXGLfchU8Ta",
  "Adventure Time: Fiona and Cake": "https://drive.google.com/drive/folders/1TWYO4e4xYDMVou36cJHASEnJdV4FFkOt?usp=drive_link",
  "Adventure Time: Fiona and Cake S1": "https://drive.google.com/drive/folders/1TKueC2iWAFibt1ih645ZWfQljYODJzs1?usp=drive_link",
  "Adventure Time: Fiona and Cake S2": "https://drive.google.com/drive/folders/1DteIHGPT-Ef8UfjO8wXG3dJivygYJVM_?usp=drive_link",
  "Aharen-San S1": "https://drive.google.com/drive/folders/1OXgcS7q8GexG3oOHxSMDuNYfUo-BMVxq?usp=share_link",
  "Aharen-San S2": "https://drive.google.com/drive/folders/1VJlXHKRS2qokKTcZLwlF9_zeSNcAi0rU?usp=share_link",
  "Aharen-San S3": "https://drive.google.com/drive/folders/1jhdpF65hUXwCRjOZKqquWB4z8L1ZpII7?usp=share_link",
  "Aharen-San S4": "https://drive.google.com/drive/folders/1DO4mX1SM8_xwqpSGkyJ7k_iHrrPbhL9J?usp=share_link",
  "Aharen-San S5": "https://drive.google.com/drive/folders/1W6TZs3tyU4wPqhFystx3cz0M7w6pzLbP?usp=share_link",
  "Aharen-San S6": "https://drive.google.com/drive/folders/1pZE3vZHVmt7REai0Q1Dz3hJM9feupEVa?usp=share_link",
  "Barbie Life in The Dreamhouse": "https://drive.google.com/drive/folders/16XksTOld5HoYI8uCgOU8aCHtlAFgERQR?usp=share_link",
  "Barbie Life in The Dreamhouse S1": "https://drive.google.com/drive/folders/12O2UQcS1Xszcb-9kn-s19ruqvk7xnrf8?usp=sharing",
  "Barbie Life in The Dreamhouse S2": "https://drive.google.com/drive/folders/1a04KgdspaWaR2xmlATayoCXIPxWfnkfA?usp=sharing",
  "Barbie Life in The Dreamhouse S3": "https://drive.google.com/drive/folders/1jgzyDn8t28foGqkEugEzz9PPRk-YLKty?usp=drive_link",
  "Barbie Life in The Dreamhouse S4": "https://drive.google.com/drive/folders/1UOb87g133XE5L5GRZ6RRYFPZSvy3SOf1?usp=drive_link",
  "Barbie Life in The Dreamhouse S5": "https://drive.google.com/drive/folders/1B3EpDItVJdqA9XSJV1aq5FFT6mb4yAxB?usp=drive_link",
  "Barbie Life in The Dreamhouse S6": "https://drive.google.com/drive/folders/1blktqO0FTXsh5r4hileTyJ-MO5o7YVS4?usp=drive_link",
  "Barbie Life in The Dreamhouse Movies": "https://drive.google.com/drive/folders/1vIh6dbEcPTvCQ2R6wsUBk0dcYHuXxdpa?usp=sharing",
  "Batman The Animated Series S1": "https://drive.google.com/drive/folders/1rrz2S1Rc7wEw4jl-6tuKd3-WRZ6mK0-W?usp=share_link",
  "Batman The Animated Series S2": "https://drive.google.com/drive/folders/1fvCT82F2qUXkC83CDjMvmSildfD1-Dtr?usp=share_link",
  "Batman The Animated Series S3": "https://drive.google.com/drive/folders/1c9yUs9q822bPBSAFpHi71mjCZnt7wawP?usp=share_link",
  "Blues Clues": "https://drive.google.com/drive/folders/1vDYQQUT_BEMS779FI2rfC-FnkoUG3g4Y?usp=share_link",
  "Blues Clues S1": "https://drive.google.com/drive/folders/1QwcWtD6GwWRa58w0wQjIweHHQJf47BOX?usp=share_link",
  "Blues Clues S2": "https://drive.google.com/drive/folders/1haRPCouOzgl1HUFzLvEq6txibXJFXSS4?usp=share_link",
  "Blues Clues S3": "https://drive.google.com/drive/folders/1TNnG3i1upD2L4oiSZnjSIb86LUFuRDqj?usp=share_link",
  "Boondocks": "https://drive.google.com/drive/folders/1ujarzaX_90FGOiRC15OmXOAgwSbdI_kA",
  "The Cuphead Show": "https://drive.google.com/drive/folders/1j_K1YV4w_sHAzwEAaUMl-qSk4qjrYSJ_?usp=share_link",
  "The Cleveland Show": "https://drive.google.com/drive/folders/12Hm67Xk3fNqRQ59pmZEBu1cq3PsC2KJH",
  "The Chi": "https://drive.google.com/drive/folders/1IMDngQ4nBi_jugA-8RS4AuQxtGgPs0cU",
  "Cobra Kai": "https://drive.google.com/drive/folders/1idzqcZUju0ADDEWnm1D9AC344rIFiGRN?usp=drive_link",
  "Cobra Kai S1": "https://drive.google.com/drive/folders/1iZZSfbqgfu8YDIP-5g8qp8XQ4al5WrDC?usp=share_link",
  "Cobra Kai S2": "https://drive.google.com/drive/folders/1PEEIDi7H157aYS5y1SPf7m4d1kM786Wn?usp=share_link",
  "Cobra Kai S3": "https://drive.google.com/drive/folders/19EBjseVtK6BcEITdVfvpxG9dbQO6mpFF?usp=share_link",
  "Everybody Hates Chris": "https://drive.google.com/drive/folders/1RUZj9WQzdEBYYLeKhD_Y9GRcZbNZMSEy?usp=sharing",
  "Euphoria": "https://drive.google.com/drive/folders/1BVkiWaMVA1mZ1J2bJcnE3_ywvNFg1IKP",
  "Family Matters": "https://drive.google.com/drive/folders/1YX2tgiy_q_-FWYwv5puLRdWOhwlJVTQ3?usp=sharing",
  "Family Guy": "https://drive.google.com/drive/folders/11W6C-Jqv9iQVasqjfiaYz77puax1UTjH?usp=drive_link",
  "Ted TV Show": "https://drive.google.com/drive/folders/1-6hBb-KZsUoc7ErXnaw2udeQv9u1THRJ?usp=drive_link",
  "Gravity Falls": "https://drive.google.com/drive/folders/1fU-FrVZ12bAZYxtxrofKkEQg2kMrIjm3?usp=sharing",
  "Gravity Falls S1": "https://drive.google.com/drive/folders/1-xSt1mLjjtY87DSpKjVbnV1P37jv_CMs?usp=sharing",
  "Gravity Falls S2": "https://drive.google.com/drive/folders/1AELIoYI4dmAAEPmAtN2mV1qXycI530dp?usp=sharing",
  "Gravity Falls S3": "https://drive.google.com/drive/folders/11yLhbzbHBC7SKbXM2J_GL4d8GD512rWU?usp=sharing",
  "Gravity Falls S4": "https://drive.google.com/drive/folders/1Z4_G8ZzFFGDmtyvNx89Jjn7kJ2BAVbeO?usp=sharing",
  "Gravity Falls S5": "https://drive.google.com/drive/folders/1NzP7wTzfC5BThyTNmw1j-BLWPnVoaNOk?usp=sharing",
  "Gravity Falls S6": "https://drive.google.com/drive/folders/15DzZ1sXWu_CEagMkG3tTFOcR1GncSkQl?usp=drive_link",
  "Harley Quinn": "https://drive.google.com/drive/folders/1ap71sKGnRDDqySR6TlfL_sXpwoM5B1Q9?usp=sharing",
  "Harvey Birdman": "https://drive.google.com/drive/folders/140J4Jyv5DvSnrcM7bI9kvqMPUmTR6vZS",
  "Hey Arnold": "https://drive.google.com/drive/folders/1tvjU4AqKfPOM_wPZA-pJsjYaOKguNaDD?usp=sharing",
  "Hey Arnold S1": "https://drive.google.com/drive/folders/1S5OH4Rs78nCVUJX7CDrv9OEuW9UOYnvl",
  "Hey Arnold S2": "https://drive.google.com/drive/folders/1BXvMJEsw-zNzRc4JHwSSOJUCv0tyee3s",
  "Hey Arnold S3": "https://drive.google.com/drive/folders/1k_nWuyVsCfmIcHAuWfrpysdHE2gwBKDK",
  "Invincible S1": "https://drive.google.com/drive/folders/1T8BbsKnX15lKidVFNmRuuKh8ErX5o5QI",
  "Invincible S2": "https://drive.google.com/drive/folders/190nl2SZwmpoE2IugUbQtxz8WrZE2Val2",
  "Invincible S3": "https://drive.google.com/drive/folders/1LUtd7dYjcxws7ymInrkX_2KZIQDBhu6q",
  "KC Undercover S1": "https://drive.google.com/drive/folders/1OJgL1LyWu3FNJvsJ-Li3Vi18iJhKB_YY?usp=sharing",
  "KC Undercover S2": "https://drive.google.com/drive/folders/1KZoRGQPBOx5HkYQ5laLMugxqSyknDkcL?usp=sharing",
  "KC Undercover S3": "https://drive.google.com/drive/folders/1K9dgECky1gy11WrMcHDI_MtXCHyyvqEh?usp=sharing",
  "Kim Possible S4": "https://drive.google.com/drive/folders/1TR8mgOxvS6H05DxGUav9TC1ri41ZdHfR?usp=sharing",
  "Lab Rats S1": "https://drive.google.com/drive/folders/1Q8TzYtSqGaM7VkSsGtPCz4PikIWZQQI7?usp=share_link",
  "Lab Rats S2": "https://drive.google.com/drive/folders/1L6Qe7kyaVM6qXoVq-p8CwFXDqXMf_62c?usp=share_link",
  "Lab Rats S3": "https://drive.google.com/drive/folders/1ErVBrquP-QgyxqNUaKkojrpg91vRUoLU?usp=share_link",
  "Lab Rats S4": "https://drive.google.com/drive/folders/1yjysqP586p72v6rHLijKWxl9TVDMKjDa?usp=share_link",
  "Miraculous": "https://drive.google.com/drive/folders/1QsOt7Qy2e3OITwrO22moBpbnv3fpQ4MQ?usp=share_link",
  "My Adventures with Superman": "https://drive.google.com/drive/folders/1tWh4y7PZNQuNaAjq-tZq3ivrhfo-fCni?usp=sharing",
  "Moon Knight": "https://drive.google.com/drive/folders/1nW610bRzpYobTHqK5k13LRkiZrRvDmZ8?usp=drive_link",
  "Ninjago": "https://drive.google.com/folderview?id=15GtJc8NKaGoZyPoRXcJjTs6ZSQfKJ-xb",
  "The Proud Family": "https://drive.google.com/drive/folders/16Wl2PBxEjlETW1FzF7zZZ8vHH9WfO3eq?usp=sharing",
  "The Power Puff Girls": "https://drive.google.com/drive/folders/1IYfB0oASMroneHQn8KansvGRnNIcYnFd?usp=sharing",
  "PJs": "https://drive.google.com/drive/u/0/folders/1RUQMqskS3ybzT6w5WQGouH9EBd5pEcTh",
  "Reccess": "https://drive.google.com/drive/folders/10frlZDyugiDyKuxu27PDvHf8r3_qxRLG?usp=share_link",
  "Rick and Morty": "https://drive.google.com/drive/folders/1ySajy4O8tRbVd_vlGCk9uyMxYHFUH-Hy?usp=share_link",
  "Spider-Man: The Animated Series": "https://drive.google.com/drive/folders/11CP20VTJqf7a2gjsLLOOu88xBropDjl2",
  "Steven Universe": "https://drive.google.com/drive/folders/1DdwOFAilBai2kDZVmRDCoNkqxTu6_E_5",
  "Steven Universe Future": "https://drive.google.com/drive/folders/1A-I64-vVIDKD14IzEh6mcMcvFmMH0NVr?usp=sharing",
  "Static Shock S1": "https://drive.google.com/drive/folders/1LquU3cM5cLHClNJYIzr3MMW3TWD7cFAf?usp=share_link",
  "Static Shock S2": "https://drive.google.com/drive/folders/1qn4z619FFkWvT6hZym1iuJnhW1F0g9sl?usp=share_link",
  "Static Shock S3": "https://drive.google.com/drive/folders/1iptDIN4iEnihXHEAX-9IgswkGgbeHoYj?usp=share_link",
  "Static Shock S4": "https://drive.google.com/drive/folders/10hP9sXsV81QG-iMZrAK1i6yy_l0hFKqb?usp=share_link",
  "Static Shock Crossover Special": "https://drive.google.com/file/d/1KdTz1iNPyMsd7qbKAmWUJKF9-mEyM8lx/view?usp=share_link",
  "Spongebob Squarepants": "https://drive.google.com/drive/folders/1QpqcZWVMlzIru0g8xf5olhMeY75YKJkk?usp=share_link",
  "Squid Game": "https://drive.google.com/drive/folders/1Wgzr-juq6L9dQN700j3P7hmdxa_-JG2y?usp=sharing",
  "Squid Game s3": "https://drive.google.com/drive/folders/15ZJ0tbruEwiRxhbue3Oria_l0i-P197a?usp=sharing",
  "Sonic X S1": "https://drive.google.com/drive/folders/1HOYzXLzNkTTfzpAWmvMWSJaJ9kLo_PZF?usp=sharing",
  "Sonic X S2": "https://drive.google.com/drive/folders/1ifub9duh9-_kCjuf6QDd2sxJFGpgf6L3?usp=sharing",
  "Sonic X S3": "https://drive.google.com/drive/folders/1_qXvuYJEjm4ZiAbgW94ykEK61g3HadCA?usp=drive_link",
  "Silo Season 1-2": "https://drive.google.com/drive/folders/1oj7nfY2x2cSNF-btmVYrG3NdPNqmkkVi?usp=drive_link",
  "The Simpsons": "https://drive.google.com/drive/folders/1bKd6gvJPWyxpDjTFvoyTBEekADdiIgE1",
  "South Park": "https://drive.google.com/drive/folders/1tXo2krTMvXr-ATSqthy55PUpRRIu1HRr?usp=sharing",
  "South Park (mines)": "https://drive.google.com/drive/folders/1PzKaoaK4blzlaoxnwC20gZoeYE5mDxWL",
  "Teen Titans S1": "https://drive.google.com/drive/folders/1EvDzzcMmYt8Wol75Ip5PtEfu78USEHH-?usp=share_link",
  "Teen Titans S2": "https://drive.google.com/drive/folders/1vqoOxi2w4IJmPelqXsTmcNCczxb6hIO7?usp=share_link",
  "Teen Titans S3": "https://drive.google.com/drive/folders/1rJxtTqih-pPjiFpF5ZbqKQmRyd9AK7jg?usp=share_link",
  "Teen Titans S4": "https://drive.google.com/drive/folders/1pDw-FSyAcNLLeSHiwyBLeg-6Pr3KQWvP?usp=share_li",
  "Teen Titans S5": "https://drive.google.com/drive/folders/1HvR1tsCeTnXVV6K1CJbfEoU0RpBLGe6h?usp=share_li",
  "Teenage Mutant Ninja Turtles S1": "https://drive.google.com/drive/folders/14rLPyemnSo-5fe6I9cXj1AvEekaBuaEb?usp=share_link",
  "Teenage Mutant Ninja Turtles S2": "https://drive.google.com/drive/folders/1TlBloSMfzBvPUUwkvRBQ-GZAjKbTjutS?usp=share_link",
  "Teenage Mutant Ninja Turtles S3": "https://drive.google.com/drive/folders/1h_pnGrifrJnpbP0H59oKqpo3dbCv5TSl?usp=share_link",
  "Teenage Mutant Ninja Turtles S4": "https://drive.google.com/drive/folders/1I_f_9tKL56cmonwKJYdpx9L8y9OqmWUd?usp=share_link",
  "Teenage Mutant Ninja Turtles S5": "https://drive.google.com/drive/folders/1DqUOZMN_Qa2APcNMLr1U8HZ4SFXdQjXB?usp=drive_link",
  "The Summer I Turned Pretty S1": "https://drive.google.com/drive/folders/1Qp2xW3xAvGAykrch5TWd2VvVBPW7d6XM?usp=drive_link",
  "The Summer I Turned Pretty S2": "https://drive.google.com/drive/folders/15r5t0S0tKORIf7YDx11-_UQgp6jI-GTS?usp=drive_link",
  "The Last Of Us S1": "https://drive.google.com/drive/folders/1MYMY-BGuKDWgmcsuWjKX6uFV0yLukSBO?usp=sharing",
  "The Last Of Us S2": "https://drive.google.com/drive/folders/1K_X6PMWG7j484hQv9nU9SYRKuR8AWx92?usp=sharing",
  "The Last Of Us": "https://drive.google.com/drive/folders/1GrakGNGC5ILz-w6_YUN1Ay_6Cuk4b-TE?usp=drive_link",
  "The X-Files": "https://drive.google.com/folderview?id=1ARvjA9abgf9qPCiAn0_A1tLjtGrNc_KP",
  "The X-Files S1": "https://drive.google.com/folderview?id=1-kchkgMKhucUCfcyTZ5j5_GS8jWu9TQC",
  "Game of Thrones S1": "https://drive.google.com/drive/folders/18a_VCltjLCHu0UIgOrfRRxq7OIj7dw9i?usp=share_link",
  "X-Men S1": "https://drive.google.com/drive/folders/1khaD7HkjetVca7uuhDEgPzWqPLwFcErQ?usp=share_link",
  "X-Men S2": "https://drive.google.com/drive/folders/13z5iRAxkLTvO3XWNBIuguRPJS-4MPHjX?usp=share_li",
  "X-Men S3": "https://drive.google.com/drive/folders/1yUkaEirDrNUIURTEF-Yi0_VKAtyBftGZ?usp=share_link",

  // Anime
  "Afro Samurai": "https://drive.google.com/drive/folders/1enWphPUwgRPYnGj2TD7XVNrG8HCc3CDm?usp=drive_link",
  "Assassination Classroom": "https://drive.google.com/drive/folders/1y294JL-QxlH03ugRf2M4342xn3qkB7c3?usp=sharing",
  "Assassination Classroom S1": "https://drive.google.com/drive/folders/1jCu_pyEtJVMPWth57nAUVcXrO_MGz4R5?usp=sharing",
  "Assassination Classroom S2": "https://drive.google.com/drive/folders/1EI_cv--0BxlKwo1CF-yXnmkPxGnnd0KN?usp=sharing",
  "Accel World": "https://drive.google.com/drive/folders/1Dt3VcMW_jxvBPSURdk503AhTGV72Ggm9?usp=share_link",
  "Akame ga Kill!": "https://drive.google.com/drive/folders/1oTiTyzGz314yeXRMChOVgDpt4lGu9Oee?usp=drive_link",
  "Boruto: Naruto Next Generations P1": "https://drive.google.com/drive/folders/190xS7bIJmSLLd-ig0jXvfcC5gOR8k59f?usp=share_link",
  "Boruto: Naruto Next Generations P2": "https://drive.google.com/drive/folders/13RVBVqUCMdF7bmlw_cdilJAzqva-r1oz?usp=sharing",
  "Boruto: Naruto Next Generations P3": "https://drive.google.com/drive/folders/1WzrW-IsN5SCAKyTDP8w0Z_6NQyRmyytf?usp=share_li",
  "Boruto: Naruto Next Generations P4": "https://drive.google.com/drive/folders/1X8bR-vFu-M6hiq0BzincFfY7uTVb_Bc9?usp=share_link",
  "Boruto: Naruto Next Generations P5": "https://drive.google.com/drive/folders/1F_w7PlH9JwMBTimo8QbO5V9d8mWEPGtU?usp=share_link",
  "Boruto: Naruto Next Generations P6": "https://drive.google.com/drive/folders/1x7vkOu6k5aaqtq5PaMM7Ue7NqmcFPLhX?usp=share_li",
  "Boruto: Naruto The Movie": "https://drive.google.com/file/d/1HvCHAWB7NhIqPbpcv3IH0r2i61AGnEBE/view?usp=share_link",
  "Beastars S1": "https://drive.google.com/drive/folders/1EgT1FVwyjuacORUG2uS2M9YPGQLCZE0v?usp=shari",
  "Beastars S2": "https://drive.google.com/drive/folders/1ENrfjeUxXh4Xhfxj6XTbUbDT24UHEJlJ?usp=share_link",
  "Bleach Box 1": "https://drive.google.com/drive/folders/1cW5SS4av8cQNVFxG8fhbCvOhfVaGPNDj?usp=sharing",
  "Bleach Box 2": "https://drive.google.com/drive/folders/1swX6ssJqHB8EZOBoL3NDkMUFH1xlbV4t",
  "Bleach Movies": "https://drive.google.com/drive/folders/1x4lgQf3YsqDg6p-oK5D2IGmVo_-mLyA0",
  "Bleach TYBW": "https://drive.google.com/drive/folders/1oc_ROQ_9WgUqwuj4HDZmzTEUs4opPKBL?usp=share_link",
  "Bleach TYBW P2": "https://drive.google.com/drive/folders/1MdDfH1NYl_N3WkfoQbIjOfRh_VNqVZYG?usp=sharing",
  "Bleach TYBW P3": "https://drive.google.com/drive/folders/1OJKMwHzQWC3Q0pJCFZXn8GYck8Iw81k5?usp=shari",
  "Blue Lock": "https://drive.google.com/drive/folders/1L_4PmRvkuqYsvLQSzMuaqRVDQg2pb9Z6?usp=drive_l",
  "Black Clover": "https://drive.google.com/drive/folders/14BM8MCLDa15ZDOoyIVI8b4Q8BAO-6sxY?usp=drive_li",
  "Black Lagoon": "https://drive.google.com/drive/folders/1vyxcp8UY0L0buinBcmYM69Bztjta9krp?usp=share_link",
  "Black Lagoon 2nd Barrage": "https://drive.google.com/drive/folders/1u14OfOTCsglGTjkX8G28neX3nBcP4QKq?usp=share_li",
  "Black Lagoon Blood Trail": "https://drive.google.com/drive/folders/1y8oTpJW57XjGekyWIo88j0fMjaSSsmtt?usp=share_link",
  "Bocchi The Rock": "https://drive.google.com/drive/folders/1UrXKPeQRzfdNq2frisCvJpNiyfID-Z0L?usp=sharing",
  "Baki S1": "https://drive.google.com/drive/folders/1YjtOVmPwbyZhMqf0W4_6x7vRIZZ4crpb",
  "Baki S2": "https://drive.google.com/drive/folders/1VL7AmdU7-Ad8SdvwSUS583sy1Sy_byxv",
  "BNA": "https://drive.google.com/drive/folders/11yw7w1FWEy4lATz9tmOjf4nvq_wpmKzB?usp=sharing",
  "Chainsaw Man Dub": "https://drive.google.com/drive/folders/1--PjiZuPtoU9Y5DFGpzGr3iR4j91pIzr?usp=drive_link",
  "Chainsaw Man Sub": "https://drive.google.com/drive/folders/14ES_2SDXFRV6n1FU880Hk8en7BMkOC_3?usp=share_link",
  "Chainsaw Man movie": "https://drive.google.com/file/d/1Nhj6LkLWuV-ab2UuR1KZxdcbgqiJIszU/view?usp=sharing",
  "Code Geass S1": "https://drive.google.com/drive/folders/1Din4-_aiz2SokjUs7dbw6JzmcQHJ9InJ?usp=share_link",
  "Code Geass S2": "https://drive.google.com/drive/folders/1z09jNjkP53A2Iq9F8ABaNLt2xeJC0t_f?usp=share_link",
  "Call of the Night": "https://drive.google.com/drive/folders/1P1zyAIRHdxMg608g1iApuTzX3pGlNPji?usp=share_link",
  "Classroom of the Elite S1": "https://drive.google.com/drive/folders/1k06WZMhpO3DOJIG913uUqVsMzYmbr3Di?usp=share_link",
  "Classroom of the Elite S2": "https://drive.google.com/drive/folders/1pnZCa4ty07vsSXKLbf8Yh6_GbtAOzqW9?usp=share_link",
  "Classroom of the Elite S3": "https://drive.google.com/drive/folders/1jz4KuQGYd4lXKnRLNCZ4jfr9w-58P0o0?usp=drive_link",
  "Cowboy Bebop": "https://drive.google.com/drive/folders/1BBQhmMmkPejoIOvEZF_-jcFOa62iF8KK?usp=share_link",
  "Dragon Ball P1": "https://drive.google.com/drive/folders/1KYg4AKv3in9mibQwMaH3btDCySKFH21g?usp=share_li",
  "Dragon Ball P2": "https://drive.google.com/drive/folders/18J68L-9TtPvI2mT_bPmdvR0WtsMyRuVb?usp=share_lin",
  "Dragon Ball P3": "https://drive.google.com/drive/folders/1cMoDq7rvEImI3AoFVLJiOWVn8lVhmUDe?usp=share_li",
  "Dragon Ball Z Raditz": "https://drive.google.com/drive/folders/18Gj3TWheHkX-fn6TfvzDyzUuu2Rv9h19?usp=drive_link",
  "Dragon Ball Z Vegeta": "https://drive.google.com/drive/folders/1VguHu2ewacxsCvLJPxWY1Vu_qbJ3E4R2?usp=drive_li",
  "Dragon Ball Z Namek": "https://drive.google.com/drive/folders/1Fka3jF5bbLk83JjzK-AfgnocLuEuDiOP?usp=drive_link",
  "Dragon Ball Z Ginyu": "https://drive.google.com/drive/folders/1829Qx9TUhtWcstw9R3_MRj3GvCJ14tjK?usp=drive_link",
  "Dragon Ball Z Frieza": "https://drive.google.com/drive/folders/1b6_q6o0VVLthmlSo-d4KCuyFVZIjKQVE?usp=sharing",
  "Dragon Ball Z Garlic Jr": "https://drive.google.com/drive/folders/1g24W5-p3iTLr5nH172HzOg18aHaDmwUV?usp=drive_li",
  "Dragon Ball Z Trunks": "https://drive.google.com/drive/folders/1krnpD6fw94PLQjDjpvuWxdBZBqeSUiVR?usp=drive_link",
  "Dragon Ball Z Androids": "https://drive.google.com/drive/folders/1otiYWmorbWMeGtEm4RmRm9H3PsSu1BoG?usp=drive_link",
  "Dragon Ball Z Imperfect Cell": "https://drive.google.com/drive/folders/1KWoo-87uYVSZd8X9ZuDYsu8WF9sj5YZK?usp=drive_li",
  "Dragon Ball Z Perfect Cell": "https://drive.google.com/drive/folders/1F7ERxGJUe_CdQ5vHmhK8pc-oUFJ9swEx?usp=drive_li",
  "Dragon Ball Z Cell Games": "https://drive.google.com/drive/folders/1wJgpk0RZFv6CaOL57GajqqLV6NFK8A7T?usp=sharing",
  "Dragon Ball Z Other World": "https://drive.google.com/drive/folders/1DY4a79TZD0bYSkWc2iYZ_NwHbRH4v86u?usp=drive_li",
  "Dragon Ball Z Great Saiyaman": "https://drive.google.com/drive/folders/1689sU8TBRwFVCPlg-dFI7oVFpADlasqz?usp=drive_link",
  "Dragon Ball Z Majin Buu": "https://drive.google.com/drive/folders/1FL90Rlt66km4bz0zO0cnKempaR79N53y?usp=drive_link",
  "Dragon Ball Z Fusion": "https://drive.google.com/drive/folders/1JMKf2e58LyRK6bJ0iJZCND74RvakAh2Q?usp=drive_lin",
  "Dragon Ball Z Kid Buu": "https://drive.google.com/drive/folders/1U19nyATfRpr6DGv0zZ7N9xCh7Qq66ADJ?usp=drive_lin",
  "Dragon Ball Z Peaceful World": "https://drive.google.com/drive/folders/1jbk09N3wE2_AnCvV6mPDJV8TtJ4C0YJt?usp=drive_lin",
  "Dragon Ball Z Return of Cooler": "https://drive.google.com/file/d/1Aqnk7lYIVauJEgro0GnfecT2s4V21QDz/view?usp=share_link",
  "Dragon Ball Z The Legendary Super Saiyan": "https://drive.google.com/file/d/1mwu1cqa92ShQu9fj_e-88z_5rxkCIvxU/view?usp=share_link",
  "Dragon Ball Super: Broly": "https://drive.google.com/file/d/1ktbXHqWnpPYZuFrg8K7YBJV2XqKFZw80/view",
  "Dragon Ball Super: Super Hero": "https://drive.google.com/file/d/1-gxJrcv5Ob2lnX1bu-nI2rniRg0p_Mmt/view?usp=share_link",
  "Dragon Ball GT S1": "https://drive.google.com/drive/folders/1mi3LQFKyR5vf1ow7_CtB1dejebU4RU2N?usp=share_lin",
  "Dragon Ball GT S2": "https://drive.google.com/drive/folders/1u-ZvJKlgtjPUu_WClZnDA-Nbmu5hDLyL?usp=share_link",
  "Dragon Ball GT S3": "https://drive.google.com/drive/folders/1WlMgS79Vtaabkh0qRneAuBPip387t5MT",
  "Demon Slayer Mugen Train": "https://drive.google.com/drive/folders/1PW_7b9wQ4YwVK1g_dSaIYDU-L8I41ywc",
  "Demon Slayer Entertainment District": "https://drive.google.com/drive/folders/1NjzSLrFC3mSK_JX6F65Yevxu0gkonhTe?usp=share_link",
  "Demon Slayer Swordsmith": "https://drive.google.com/drive/folders/1SDfC_6XpQSWT2BBEZYDwt9tdiZCeaf-T?usp=share_lin",
  "Demon Slayer Swordsmith Dub": "https://drive.google.com/drive/folders/1yhbotG1QOv-roTM4tS6tZFjglZSPgaEt?usp=sharing",
  "Death Note": "https://drive.google.com/drive/folders/166tNe4UUWgYROWK4DwhtZKxgrpFZZAm5?usp=drive_link",
  "Don’t Toy With Me, Miss Nagatoro S1": "https://drive.google.com/drive/folders/1XSGMZ8cGncuqGdZGqTT32gbrOn6FkZvc?usp=share_l",
  "Don’t Toy With Me, Miss Nagatoro S2": "https://drive.google.com/drive/folders/1iaU1mOEjxkk8zKxwfLGnREfh_rJGI8uv?usp=share_link",
  "Dandadan S1": "https://drive.google.com/drive/folders/1sl2rZUanjydVYDma7HmlLxX4Uvz_sJpG?usp=sharing",
  "Dandadan S2": "https://drive.google.com/drive/folders/15vy-gWZQL3HukQcDhEqL5Z0Y5Ukxriod?usp=sharing",
  "Delicious in Dungeon": "https://drive.google.com/drive/folders/1-WRkUvVifVomqX101ohL_4k_2EBN4yk-?usp=sharing",
  "Digimon Adventure 01": "https://drive.google.com/drive/folders/1mR_Qg3CS17ot_Kwe2WqKl-d-XxbTgsw0?usp=share_li",
  "Digimon Our War Game": "https://drive.google.com/file/d/1Et2Obe_7Cd_mbp6yje4JbpK5efzPBcQB/view?usp=share_link",
  "Digimon Adventure 02": "https://drive.google.com/drive/folders/1_-D3JFUmFlj3wkUcMgjil769wo8VSizy?usp=share_link",
  "Digimon Tamers": "https://drive.google.com/drive/folders/1yoOzJd6juXkhkwkL6SeWSJRPX0d5DjH0?usp=share_lin",
  "Digimon Frontier P1": "https://drive.google.com/drive/folders/1OnuDQP07S7k2ur5VAJhGXNbBj0uSjj2T?usp=share_lin",
  "Digimon Frontier P2": "https://drive.google.com/drive/folders/1VRL5GPMKauk6kqZe1JyLY7BYF7T_9tNr?usp=share_li",
  "Digimon Frontier P3": "https://drive.google.com/drive/folders/1H6cJ2pH5PfKX_MVKD_pNB7K3dxuJg6uR?usp=share_l",
  "Digimon Data Squad": "https://drive.google.com/drive/folders/1huH1lPop9dPOkEUT3Lf71B6jfqrlB0W9?usp=share_link",
  "Digimon Hurricane Touchdown": "https://drive.google.com/file/d/1SPqRTCc92O2MuTBWTCegCQ8P4u1oAWbt/view?usp=share_l",
  "Digimon Revenge of Diaboramon": "https://drive.google.com/file/d/1XfqbnUIjOziPY7D-wQ3Sqb6HwdzEOhaW/view?usp=drive_link",
  "Digimon Last Evolution Kizuna": "https://drive.google.com/file/d/1QZef7kh-P6arod3wTDSiYPRUrrnBxM7i/view?usp=drive_link",
  "Digimon Fusions P1": "https://drive.google.com/drive/folders/1pEO-D9a46f2CaR4w8mP4w7SoHyI3qTCB?usp=share_li",
  "Digimon Fusions P2": "https://drive.google.com/drive/folders/1tH6mPDkio9-eJmBkLtBcRR0fXo9VxjlY?usp=share_link",
  "Digimon Adventure 2020": "https://drive.google.com/drive/folders/1bUWpxgG_Ni9qNmx8Q4MzaWhgm8kEtz-l?usp=share_li",
  "Digimon Ghost Game": "https://drive.google.com/drive/folders/1zI69BM-CprCG04aNgDXRTwD5MmHujW0I?usp=share_link",
  "Danganronpa": "https://drive.google.com/drive/folders/1rEGjDXtZdvPoV_c7baKoLolOHlqIc_DM?usp=share_link",
  "Dr Stone S1": "https://drive.google.com/drive/folders/1pDU6-K8yH8Gx5rWx4p2OhXPqEoVezgH2?usp=drive_li",
  "Dr Stone S2": "https://drive.google.com/drive/folders/1rOTyOYnArhrByQ7ql1mMcSE9AHYq2FEi?usp=drive_lin",
  "Dr Stone S3": "https://drive.google.com/drive/folders/1-4pOBXRsglQkcRCaA2JrXRr3SKORCYKy?usp=share_li",
  "Dr Stone Ryusui": "https://drive.google.com/file/d/1s_A8Ufa-flY3F0ch4WzEcbhv396q6VQM/view?usp=drive_link",
  "Fullmetal Alchemist": "https://drive.google.com/drive/folders/1HJchHHAgQ7_YPwt4K-mFMpFVoaqimFxv?usp=drive_li",
  "Fullmetal Alchemist: Brotherhood": "https://drive.google.com/drive/folders/1UxoXY76-yRepcoCoTln92B38CuQZWAnV?usp=sharing",
  "Fushigi Yuugi": "https://drive.google.com/drive/folders/11QoMw6ZDt2qc7TtEjX8qnRr87sU4_mUC?usp=share_li",
  "FLCL": "https://drive.google.com/drive/folders/17ZwTmR4mY0Dskm6IIdjJLhlO6VpZMBUY?usp=share_li",
  "Fruits Basket S1": "https://drive.google.com/drive/folders/1u0uznDfGZbWDOAZJxvP87VvnWKGvcllk",
  "Fruits Basket S2": "https://drive.google.com/drive/folders/1krrak4A2Wl59jqT2E3fy9Do1RYgeep80",
  "Fruits Basket S3": "https://drive.google.com/drive/folders/1f4fGOow6MparOmnaQbq-zV0akyzcGoOb",
  "Frieren": "https://drive.google.com/drive/folders/1FdJmWDqhtbTywSnTdIXP6M1_V1waz7Ys?usp=sharing",
  "Ghost Stories": "https://drive.google.com/drive/folders/1FoMJZ207BaoEBhB1puSXo-Xozhf2jxsA?usp=share_link",
  "Gurren Lagann": "https://drive.google.com/drive/folders/1J44weqmCOZ2jsj9vlfft5-a_IHgfREk-?usp=sharing",
  "Hunter x Hunter Box 1": "https://drive.google.com/drive/folders/1qFwHtAeqsZbchq1pkUisvhTillNF3dvv?usp=share_link",
  "Hunter x Hunter Box 2": "https://drive.google.com/drive/folders/1VizfC5Jb33AEsHOOmDe_MaY71B3z5Scz?usp=share_li",
  "High Rise Invasion": "https://drive.google.com/drive/folders/1B2wrcAgYVpr9kyyshPMzZlymB2KeErfe?usp=share_link",
  "High Card": "https://drive.google.com/drive/folders/1W_mQB8z3k4MewHAGJrfdoikA0X9-3RDK?usp=share_li",
  "High School of the Dead": "https://drive.google.com/drive/folders/1dYLldMCPrRMrV5Ke8hTWVQ8WwI8oB46F?usp=share_link",
  "Horimiya": "https://drive.google.com/drive/folders/153Fbd_LCVOr4d96NXENTrBL-DBahGs-h?usp=sharing",
  "Horimiya Piece Sub": "https://drive.google.com/drive/folders/1dyi4XMxCjkNDEHQSvHbK-x0sALxDF96t?usp=drive_link",
  "Horimiya Piece Dub": "https://drive.google.com/drive/folders/1C4NRoMtXuYhbzjMvmf4GV_XLfTlXa5k3?usp=sharing",
  "Hell's Paradise": "https://drive.google.com/drive/folders/1pZKT0MMp30JToJKbxWrO6-h2DGwIgm95?usp=drive_li",
  "Hellsing": "https://drive.google.com/drive/folders/1UNKc2Yhib4PrzAYpGtkMOxyxsH6_2JLL?usp=drive_link",
  "Hajime No Ippo S1": "https://drive.google.com/drive/folders/1LMTt7FupplMrBsKhivRqnGMh0sft1dNK",
  "Hajime No Ippo S2": "https://drive.google.com/drive/folders/1CK00O_BYeIuiM7b-ZO5mfu9Gx4fgpNKi",
  "Hajime No Ippo S3": "https://drive.google.com/drive/folders/1PN-jSRahKDorrFDdHYff7okU9fkMt0P2",
  "Inuyasha": "https://drive.google.com/drive/folders/1UqQGwxmg5ctkXpFc9cfgczLn_HbGmGbw?usp=drive_li",
  "Inuyasha Movie 1": "https://drive.google.com/drive/folders/1EJdjU65AtMbsMwUSBKA_aakHGeggN5k7?usp=drive_li",
  "Inuyasha Movie 2": "https://drive.google.com/drive/folders/1Mb7flX7iqAdjpsVfb2gVI44GLGBl8Jan?usp=drive_link",
  "Inuyasha Movie 3": "https://drive.google.com/drive/folders/1OKRpVNiqwsSH6W-MEsQrtRw1ADxv_FZw?usp=drive_l",
  "Inuyasha Movie 4": "https://drive.google.com/drive/folders/1CVCT0JL6bLeP6uyOaqI7RALZtVppznon?usp=drive_link",
  "Inuyasha Final Act 1-13": "https://drive.google.com/drive/folders/1PzWAkHlfF2S2pn2OfUvNPXuucu7ddMMa?usp=drive_lin",
  "Inuyasha Final Act 14-26": "https://drive.google.com/drive/folders/1nahnQHhBmAFG3ai4rQwUTLq9G9eAC6hs?usp=sharin",
  "I Want To Eat Your Pancreas": "https://drive.google.com/drive/folders/1Xt7ZbY1LLlFLCWVKd4cYs6pdG-PG3lft?usp=share_link",
  "Jujutsu Kaisen S1": "https://drive.google.com/drive/folders/1uxszC0gNTvkWicUU-TAUfCdGy7I8g0_y?usp=drive_link",
  "Jujutsu Kaisen S2": "https://drive.google.com/drive/folders/1a59lEnayevGMXtPyVn52II3rdorI6aBG?usp=drive_link",
  "Jujutsu Kaisen 0": "https://drive.google.com/file/d/1mU5HS6GK3_xVtpmjVU3mhY0dN3iv7ZO7/view?usp=drive_link",
  "Kaguya Sama S1": "https://drive.google.com/drive/folders/1Ry3bVId9HQJcIQPMzlmXOF9lb2Ld3TED?usp=drive_lin",
  "Kaguya Sama S2": "https://drive.google.com/drive/folders/1iNg_2UaNQnmuEVCGXBAKbS3Kxm8JQcZt?usp=drive_",
  "Kaguya Sama S3": "https://drive.google.com/drive/folders/13bTt60x8tJAkMVj5Dl812hzULXjuLuhf?usp=drive_link",
  "Konosuba S1": "https://drive.google.com/drive/folders/1rDoBGwTIFsbwoN8J-NFIfhi5_4yFQomx",
  "Konosuba S2": "https://drive.google.com/drive/folders/1GB2mqc8xZP-speckOq9mrHaODJERiTKq",
  "Konosuba S3": "https://drive.google.com/drive/folders/1cTyfez_Z5hpZktCbbHOGKqmi1dWSkNIp?usp=sharing",
  "Konosuba Movie": "https://drive.google.com/file/d/1Rohh1Fyx5OW9LvpAMytZl1-2gM_IbCgo/view?usp=sharing",
  "Komi Can’t Communicate S1": "https://drive.google.com/drive/folders/1VsPKRjlrawm0bdv-1Snstp0PTtcxi_3U",
  "Komi Can’t Communicate S2": "https://drive.google.com/drive/folders/1SgZ_eimnMG9lWM7IJTOmpZeFGHYYmLPn?usp=shari",
  "Kakegurui S1": "https://drive.google.com/drive/folders/1dmaDcwLdvlDKg7mcdUH4q_zWzTYZRaRn?usp=sharin",
  "Kakegurui S2": "https://drive.google.com/drive/folders/1khYgXBBJX1aKATaEIc-XGHfZNxHErs_r?usp=sharing",
  "Kakegurui Twin": "https://drive.google.com/drive/folders/1JVWSNv-LWxX-UulYoT3Ht6HCpYcqngK-?usp=share_lin",
  "Kimi Ni Todoke S1": "https://drive.google.com/drive/folders/1f-qHhQJQevZV0nGLBFL8hNkUXyH1xP4b?usp=sharing",
  "Kimi Ni Todoke S2": "https://drive.google.com/drive/folders/1RmQ_F9MYa369X2GN5rZF2R5J5AdbjXl_?usp=sharing",
  "Kill La Kill": "https://drive.google.com/drive/folders/12VdhYQ9x9gsdUqgHzRuRIN6Z6nFr9W_s?usp=sharing",
  "Kaiju No 8": "https://docs.google.com/folderview?id=1k8RAbYxWLt1_b0UmY5lMFUw2T--WhHAK",
  "Lookism": "https://drive.google.com/drive/folders/1qYz8HXhYOwR-TOWgN4E4yKAbgoqI8kUS?usp=share",
  "Loving Yamada at Lv999": "https://drive.google.com/drive/folders/1sFJzb5jLL9jTR3eKLBP8obqdJOeNzwub?usp=share_link",
  "Mob Psycho 100 1-2": "https://drive.google.com/drive/folders/19FPsnL-DhTC3JRBnMfNrcGXfpIj2gli_",
  "Mob Psycho 100 S3": "https://drive.google.com/drive/folders/1Lt1ok2c4SKmf3m2KJsjD2t_xqeecaKdZ",
  "My Hero Academia S1": "https://drive.google.com/drive/folders/1v8BMG58ZRYNIWSgIxxHezBSCc11XIBIv?usp=share_li",
  "My Hero Academia S2": "https://drive.google.com/drive/folders/1hsHIuM_1TjMEMQQDobvz4xw_qi45SVCY?usp=share_li",
  "My Hero Academia S3": "https://drive.google.com/drive/folders/1cnArp_7jQz70PwBTiRLJO5_xrYVGgTGl?usp=share_link",
  "My Hero Academia S4": "https://drive.google.com/drive/folders/1_JqpVKIvQG14ANk8wBLfq_Rg69mPnZwf?usp=share_li",
  "My Hero Academia S5": "https://drive.google.com/drive/folders/1fml71A9f4FzAQwq9FDYyv25vAFoHhsWE?usp=share_li",
  "My Hero Academia S6": "https://drive.google.com/drive/folders/11BmJJ1cswuNAYeoDcYl9dFW1QngvClVT?usp=share_li",
  "My Hero Academia S7": "https://drive.google.com/drive/folders/1GxLXe6eFM6DGTNFpwf-rZhiDL_tCkf8E?usp=share_link",
  "Mushoku Tensei P1": "https://drive.google.com/drive/folders/1-mMJE-niE3RaDu_VUt2upo-tAWdLTvb1?usp=drive_link",
  "Mushoku Tensei P2": "https://drive.google.com/drive/folders/1qJIK-0USBr9x4PazdPEx2ffi4tp2_f2q?usp=share_link",
  "Mushoku Tensei S2": "https://drive.google.com/drive/folders/10Hkw-M5-fOyf8pWP2DHSmFJWX-tH_-TP?usp=sharing",
  "Monster": "https://drive.google.com/drive/folders/1B8PuNaiBa0d5VXEGW0OsgnnH0QzWkdCa?usp=share",
  "Mysterious Girlfriend X": "https://drive.google.com/drive/folders/1reaRP9ULhOAImjC_Iev9YVkNc_y87hxg?usp=share_link",
  "Made In Abyss S1": "https://drive.google.com/drive/folders/1JneEAxAehzDrWqzxu-EyWtd210OQBqwu?usp=sharing",
  "Made In Abyss S2": "https://drive.google.com/drive/folders/1_SUt3usX6klCJH_Njr7GiLSRHyI8Hj33?usp=share_link",
  "Masamune-kun’s Revenge S1": "https://drive.google.com/drive/folders/1ERYBo6bYs1A9suFa9mhMKIqXXk6R6FCD?usp=drive_l",
  "Neon Genesis Evangelion": "https://drive.google.com/drive/folders/1zcx8VNuwn20pA7LPrYeD-Lh8FU-cJukw?usp=share_lin",
  "Nokotan": "https://drive.google.com/drive/folders/1wLa94fdNpe9uFoLRZstYSIOg7fgsJOID?usp=sharing",
  "Ouran High School Host Club": "https://drive.google.com/drive/folders/1aJLOV7FTJtjcublD7WIqkq3cAdFGDnIA",
  "One Punch Man S1": "https://drive.google.com/drive/folders/1yGjMeMX0_1vUHa6XbpszYGe5yLqYLKRc?usp=share_l",
  "Oshi No Ko S1": "https://drive.google.com/drive/folders/1OSlbwgzeF6aoZJg6StUqx5zYQ8rs58md",
  "Oshi No Ko S1 DUB": "https://drive.google.com/drive/folders/178TtrpkiQmhnJagf-z_otLDEmLUdRD4Z",
  "Parasyte": "https://drive.google.com/drive/folders/1xUQrP52EaSY5apdQ6vX6jAPMHziv7yfN?usp=share_lin",
  "Pokémon S1": "https://drive.google.com/drive/folders/1WxVqcNBPFx_6Ig4pjJ3hU-KuEsNESrzP?usp=drive_link",
  "Pokémon S2": "https://drive.google.com/drive/folders/1sw8EU1mOs7PRaf0aGH2Th6KRAKKDlR7q?usp=drive_l",
  "Pokémon S3": "https://drive.google.com/drive/folders/17msHXnN1aYSwu2cwnKOY5vzsmzitriKx?usp=drive_link",
  "Pokémon S4": "https://drive.google.com/drive/folders/1eWdGikeUtDge9jgnjnJY1BqgrZZ17TNp?usp=drive_link",
  "Pokémon S5": "https://drive.google.com/drive/folders/1kK-SmHN50-vtDaDo9mvBySwlBjHsyfH_?usp=drive_link",
  "Pokémon S6": "https://drive.google.com/drive/folders/1VdER021ngOG3XvBwErEzkIjQSevuhl0Y?usp=drive_link",
  "Pokémon S7": "https://drive.google.com/drive/folders/18VN9uhYVN-MsHIbVQaTsd2sH6eFHs2IT?usp=drive_lin",
  "Pokémon S8": "https://drive.google.com/drive/folders/1e6GiwagZFCczS6F7EqiYfE_Gzh9PuOK2?usp=drive_lin",
  "Pokémon S9": "https://drive.google.com/drive/folders/1s3k4aEnKxAdq3FfAOYJK3Zv_fmofpZsZ?usp=drive_link",
  "MewTwo Strikes Back": "https://drive.google.com/file/d/1oUNzcsvyWAjS4sUR9-FRNShj-F5AcMim/view?usp=drive_link",
  "Your Name": "https://drive.google.com/file/d/1-eSl82lH3MQlanK5LebatbIDCGnoIJlr/view?usp=drive_link",
  "Solo Leveling": "https://drive.google.com/drive/folders/12tApujIKnQjaSlTRchrO0AZ8WhvhaNtl",
  "Attack On Titan": "https://drive.google.com/drive/folders/1B46EboOes_-kq6jvdL1KSFAhrFMNk4Lj",
  "Demon Slayer": "https://drive.google.com/drive/folders/1mmBVdj-oKIC0aSdOcMcEnQ129-rKimKo",
  "The Promised Neverland": "https://drive.google.com/drive/folders/1FhcZTDf0G1Fy6RlpcrsrSC-Pg63UZOqq",
  "Sailor Moon": "https://drive.google.com/drive/folders/1zZ9tlSypaIBKwM-1H9DjZA-P9Vyh6P-1",
  "Berserk": "https://drive.google.com/drive/folders/14Ri_EP2Q6HxWJQbU97ZEAjSc9MfTmKI3",
  "Bleach": "https://drive.google.com/drive/folders/1wvJR_lTZCJ_b9QId26AW0X6aCfBMBQlB",
  "Sakamoto Days": "https://drive.google.com/drive/folders/19DUxPkVk-4ixzNcLMIMjiQS5Zs6aCm7T",
  "Spy x Family": "https://drive.google.com/drive/folders/1GZKLsvSvgvHfM3CXg4DrCh4d0tGb0NLX",
  "Kingdom Hearts": "https://drive.google.com/drive/folders/1IMqZo3XL_Go8PYa8i5iMH-3w5kEE-fTC",
  "Dr. Stone": "https://drive.google.com/drive/folders/1uiqdQByTMfGeeQV8ut3o0BYuZu52CR7i",
  "Darling In The Franxx": "https://drive.google.com/drive/folders/12P8fxgEN_fJlbJ4z_X6lorJUud7Qc0jS",
  "Legend of Zelda": "https://drive.google.com/drive/folders/1DiPmxSEnK8mffjlJv-Mrka-Pg_qw5Zlj",
  "Yu Yu Hakusho": "https://drive.google.com/drive/folders/1sqibKs8lPGa1pmostQQMafjRwhcF1hvg",
  "My Hero Academia": "https://drive.google.com/drive/folders/1Ty8TRLsEhVwDR0mMXe9bvZw2Mjgqbfr7",
  "My Hero Academia 377+": "https://drive.google.com/drive/folders/1psqilwlG-rU_MRv5rn-ac-8UqNnQDor1",
  "Dandadan": "https://drive.google.com/u/0/folders/1u-a-NGgGUHD-h5RBtVkYnp8TwJosaJIe",
  "Pokémon Adventures": "https://drive.google.com/drive/folders/1QKSJxCrNtvP7Li3lLz0GhuTV7WrbXMiS",
  "Chainsaw Man": "https://drive.google.com/drive/folders/16KZIqJMkvzHeX8TsP_tOoLHSoqJwuWYf"
};

// Fuzzy Link Matching: Normalizes strings to find links even if there are small typos
const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const findLink = (title: string) => {
  // 1. Direct match
  if (LINK_DB[title]) return LINK_DB[title];
  
  // 2. Fuzzy match (ignore case, spaces, punctuation)
  const normTitle = normalize(title);
  const matchedKey = Object.keys(LINK_DB).find(k => normalize(k) === normTitle);
  
  // 3. Search Fallback
  return matchedKey ? LINK_DB[matchedKey] : getSearchLink(title);
};

const extractYear = (title: string): number | undefined => {
  const match = title.match(/\b(19|20)\d{2}\b/);
  return match ? parseInt(match[0]) : undefined;
};

const guessGenre = (title: string): string[] => {
  const lower = title.toLowerCase();
  const genres = new Set<string>();
  
  if (lower.includes('action') || lower.includes('batman') || lower.includes('avengers') || lower.includes('spider') || lower.includes('transformer') || lower.includes('wick') || lower.includes('fast') || lower.includes('furious') || lower.includes('godzilla') || lower.includes('kong') || lower.includes('deadpool') || lower.includes('x-men') || lower.includes('blade')) genres.add('Action');
  if (lower.includes('adventure') || lower.includes('jumanji') || lower.includes('uncharted') || lower.includes('dune') || lower.includes('star wars') || lower.includes('trek') || lower.includes('harry potter') || lower.includes('lord of the rings') || lower.includes('hobbit') || lower.includes('pirates')) genres.add('Adventure');
  if (lower.includes('comedy') || lower.includes('funny') || lower.includes('hangover') || lower.includes('superbad') || lower.includes('mean girls') || lower.includes('barbie') || lower.includes('shrek') || lower.includes('minions') || lower.includes('despicable') || lower.includes('alvin')) genres.add('Comedy');
  if (lower.includes('horror') || lower.includes('dead') || lower.includes('scream') || lower.includes('saw') || lower.includes('conjuring') || lower.includes('insidious') || lower.includes('nun') || lower.includes('quiet place') || lower.includes('fnaf') || lower.includes('halloween') || lower.includes('chucky') || lower.includes('terrifier') || lower.includes('smile')) genres.add('Horror');
  if (lower.includes('family') || lower.includes('disney') || lower.includes('pixar') || lower.includes('dreamworks') || lower.includes('toy story') || lower.includes('frozen') || lower.includes('moana') || lower.includes('encanto') || lower.includes('mario') || lower.includes('sonic') || lower.includes('despicable me') || lower.includes('madagascar') || lower.includes('ice age') || lower.includes('finding nemo')) genres.add('Family');
  if (lower.includes('drama') || lower.includes('godfather') || lower.includes('shawshank') || lower.includes('schindler') || lower.includes('fight club') || lower.includes('creed') || lower.includes('rocky') || lower.includes('forrest gump') || lower.includes('gladiator')) genres.add('Drama');
  if (lower.includes('scifi') || lower.includes('sci-fi') || lower.includes('alien') || lower.includes('avatar') || lower.includes('matrix') || lower.includes('inception') || lower.includes('interstellar') || lower.includes('jurassic') || lower.includes('transformers') || lower.includes('terminator')) genres.add('Sci-Fi');
  if (lower.includes('romance') || lower.includes('love') || lower.includes('notebook') || lower.includes('titanic') || lower.includes('twilight') || lower.includes('your name')) genres.add('Romance');
  if (lower.includes('anime') || lower.includes('naruto') || lower.includes('one piece') || lower.includes('bleach') || lower.includes('dragon ball') || lower.includes('demon slayer') || lower.includes('jujutsu') || lower.includes('solo leveling') || lower.includes('chainsaw') || lower.includes('kaisen')) genres.add('Anime');
  
  if (genres.size === 0) genres.add('Uncategorized');
  return Array.from(genres);
};

const guessRating = (title: string): number => {
  // Deterministic pseudo-random rating based on title
  let hash = 0;
  for (let i = 0; i < title.length; i++) {
    hash = ((hash << 5) - hash) + title.charCodeAt(i);
    hash |= 0;
  }
  // Map to 6.0 - 9.8 range
  const normalized = Math.abs(hash) % 39; // 0-38
  return Number((6.0 + (normalized / 10)).toFixed(1));
};

// Generate Library Items from the massive Link DB + existing lists
const generateLibrary = (keys: string[], category: 'movie' | 'anime' | 'manga' | 'tv') => {
  return keys.map(t => ({
    t,
    l: findLink(t),
    img: getPlaceholderImg(t),
    year: extractYear(t),
    genre: guessGenre(t),
    rating: guessRating(t)
  }));
};

// Movies: Use keys from LINK_DB that aren't TV seasons
// Categorize based on the structure of LINK_DB
const ALL_DB_KEYS = Object.keys(LINK_DB);

const animeStartIndex = ALL_DB_KEYS.indexOf("Afro Samurai");

const ANIME_KEYS = ALL_DB_KEYS.slice(animeStartIndex);

export const MOVIES_DATA: LibraryItem[] = MOVIES.map(movie => ({
  t: movie.title,
  l: movie.link,
  img: movie.imageUrl,
  year: parseInt(movie.year) || undefined,
  genre: guessGenre(movie.title),
  rating: guessRating(movie.title)
}));
export const ANIME_DATA: LibraryItem[] = ANIME.map(anime => ({
  t: anime.title,
  l: anime.link || '',
  img: anime.imageUrl,
  links: anime.links,
  genre: guessGenre(anime.title),
  rating: guessRating(anime.title)
}));
export const TV_DATA: LibraryItem[] = TV_SHOWS.map(tv => ({
  t: tv.title,
  l: tv.link,
  img: tv.imageUrl,
  links: tv.links,
  genre: guessGenre(tv.title),
  rating: guessRating(tv.title)
}));

export const MANGA_DATA: LibraryItem[] = MANGA.map(manga => ({
  t: manga.title,
  l: manga.url,
  img: manga.imageUrl,
  year: parseInt(manga.year) || undefined,
  genre: guessGenre(manga.title),
  rating: guessRating(manga.title)
}));


export const APPS_DATA: LibraryItem[] = [
  { t: "YouTube", l: "https://youtube.com", img: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80", year: 2005, genre: ["Video", "Social"], rating: 9.8 },
  { t: "Discord", l: "https://discord.com", img: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&q=80", year: 2015, genre: ["Chat", "Social"], rating: 9.5 },
  { t: "TikTok", l: "https://tiktok.com", img: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=800&q=80", year: 2016, genre: ["Social", "Video"], rating: 8.9 },
  { t: "GitHub", l: "https://github.com", img: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&q=80", year: 2008, genre: ["Development", "Code"], rating: 9.7 },
  { t: "ChatGPT", l: "https://chat.openai.com", img: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80", year: 2022, genre: ["AI", "Tools"], rating: 9.9 },
];

export const CLOAK_OPTIONS = [
  { id: 'none', name: 'None', icon: '❌', title: 'MONOCHROME', favicon: '/favicon.ico' },
  { id: 'google', name: 'Google', icon: '🔍', title: 'Google', favicon: 'https://www.google.com/favicon.ico' },
  { id: 'drive', name: 'Google Drive', icon: '📂', title: 'My Drive - Google Drive', favicon: 'https://ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png' },
  { id: 'canvas', name: 'Canvas', icon: '🎓', title: 'Dashboard', favicon: 'https://du11hjcvx0uqb.cloudfront.net/br/dist/images/favicon-e10d657a73.ico' },
  { id: 'classroom', name: 'Google Classroom', icon: '🏫', title: 'Classes', favicon: 'https://ssl.gstatic.com/classroom/favicon.png' },
  { id: 'zoom', name: 'Zoom', icon: '📹', title: 'Zoom Meetings', favicon: 'https://st1.zoom.us/zoom.ico' },
];
export const PROXIES_DATA: ProxyItem[] = [
  { url: "https://monochrome.tf/", name: "Monochrome" },
  { url: "https://pizzatowerplay.com/", name: "Pizza Tower" },
  { url: "https://mathhomeworkhelp.pythagorasweb.com.ar/index.html", name: "Math Homework Help" },
  { url: "https://cookiss4u.wasmer.app/", name: "Cookiss4u" },
  { url: "https://ncdsb.netlify.app/search", name: "NCDSB Proxy" },
  { url: "https://thatdogis.wagging.dev/", name: "Wagging Dev" },
  { url: "https://interstellarpro.netlify.app/", name: "Interstellar Pro" },
  { url: "https://crazycattle3d.lol/", name: "Crazy Cattle 3D" },
  { url: "https://undeblocked-main.my.canva.site/home", name: "Undeblocked Main" },
  { url: "https://sodium.z1g.top/welcome", name: "Sodium Z1g" },
  { url: "https://amongusinreallifesussus.netlify.app/", name: "Among Us Proxy" },
  { url: "https://helpful-brioche-c830e8.netlify.app/gxmes/", name: "Helpful Brioche" },
  { url: "https://pixel-physics.seanmorr.is/", name: "Pixel Physics" },
  { url: "https://school.data.ecodryfruits.com/main.html", name: "School Data" },
  { url: "https://helios-8lm.pages.dev/", name: "Helios 8LM" },
  { url: "https://zazzle-1.global.ssl.fastly.net/", name: "Zazzle Fastly" },
  { url: "https://loungef2x.web.app/", name: "Lounge F2X" },
  { url: "https://banana.global.ssl.fastly.net/", name: "Banana Fastly" },
  { url: "https://pn.org.savitaipaleenmusiikkikoulu.fi/", name: "PN Org" },
  { url: "https://geogappu.chrisbaxmann.com/", name: "Geogappu" },
  { url: "https://learnmaths.ovieags.gob.mx/", name: "Learn Maths" },
  { url: "https://awesome.martinwguy.net/", name: "Awesome Martin" },
  { url: "https://strange.martinwguy.net/", name: "Strange Martin" },
  { url: "https://epic.tomaszu.com/", name: "Epic Tomaszu" },
  { url: "https://eglobaleducation.com/", name: "E-Global Education" },
  { url: "https://wow.aliexpress.nl/", name: "Wow Aliexpress" },
  { url: "https://grail.allenbarnes.org/", name: "Grail Allen Barnes" },
  { url: "https://island.zoomzoomblooms.com/", name: "Island Zoom" },
  { url: "https://gravity.roseflame.com/", name: "Gravity Roseflame" },
  { url: "https://pn.savitaipaleenmusiikkikoulu.fi/", name: "PN Savitaipaleen" },
  { url: "https://sci.grasic.info/", name: "Sci Grasic" },
  { url: "https://infoo.infotechnology.com/", name: "Infoo Tech" },
  { url: "https://stuff.qjdy.net/", name: "Stuff QJDY" },
  { url: "https://ee.rxtech.cl/", name: "EE RXTech" },
  { url: "https://test-schoolhfhjc.misem.or.id/", name: "Test School" },
  { url: "https://test-56778679.easychargebatteries.com/", name: "Test Batteries" },
  { url: "https://watervapor.space/", name: "Water Vapor" },
  { url: "https://education-live.com/", name: "Education Live" },
  { url: "https://canvasbackpackstore.com/", name: "Canvas Backpack" },
  { url: "https://pn.boredom.apertura.com/", name: "PN Boredom" },
  { url: "https://pizza.frogiee.one.cdn.cloudflare.net/" },
  { url: "https://hcstemm.org/", name: "HC Stemm" },
];

export const PARTNERS_DATA: PartnerItem[] = [
  { 
    name: "カービィアーケード", 
    owner: "SAM", 
    url: "https://sites.google.com/view/fus3-bomb/page", 
    urls: [
      { name: "Google Sites", url: "https://sites.google.com/view/fus3-bomb/page" },
      { name: "GitHub Pages", url: "https://mkplaza.github.io/" }
    ],
    banner: "https://preview.redd.it/what-are-your-favorite-meta-knight-battle-themes-and-v0-2rludfrd5hqb1.jpg?width=640&crop=smart&auto=webp&s=9a5cf8aac407cfafbcea666f0baca6293dfa2123",
    avatar: "https://cdn.jsdelivr.net/gh/MKPlaza/MKPlaza.github.io@main/Meta_Knight_Logo.webp"
  }
];

export const STAFF_DATA: StaffMember[] = [
  { name: "Sols", role: "Owner", img: "https://i.pinimg.com/1200x/90/54/72/9054723fa92af09702e7e72b44f0c232.jpg", link: "https://guns.lol/ohsols" },
  { name: "xsviiera", role: "Co-Owner", img: "https://i.pinimg.com/736x/de/7d/d1/de7dd1dac309810a55559f1b4bac930a.jpg", link: "https://guns.lol/iviera" }
];
