
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { translateText } from '../services/gemini';

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'en-US': {
    'Theme': 'Theme',
    'Cloak': 'Cloak',
    'Language': 'Language',
    'Changes apply instantly.': 'Changes apply instantly.',
    'Theme Name': 'Theme Name',
    'Background': 'Background',
    'Foreground': 'Foreground',
    'Card': 'Card',
    'Border': 'Border',
    'Primary': 'Primary',
    'Accent': 'Accent',
    'Reset to Default': 'Reset to Default',
    'Cloak Methods': 'Cloak Methods',
    'Hide your activity in an about:blank tab.': 'Hide your activity in an about:blank tab.',
    'Cloak Site': 'Cloak Site',
    'Tab Title': 'Tab Title',
    'Tab Icon (URL)': 'Tab Icon (URL)',
    'Open Now': 'Open Now',
    'Pick your preferred locale for time formatting and future language support.': 'Pick your preferred locale for time formatting and future language support.',
    'English is the default. Other options adjust locale formatting.': 'English is the default. Other options adjust locale formatting.',
    'Military Time': 'Military Time',
    'Uses 24-hour clock format for the time widget.': 'Uses 24-hour clock format for the time widget.',
    'Time Zone': 'Time Zone',
    'Select a specific time zone or use your system default.': 'Select a specific time zone or use your system default.',
    'Custom': 'Custom',
    'Default': 'Default',
    'System Default': 'System Default',
    'Home': 'Home',
    'Devs': 'Devs',
    'Donate': 'Donate',
    'Movies': 'Movies',
    'TV Shows': 'TV Shows',
    'Animes': 'Animes',
    'Mangas': 'Mangas',
    'Anime': 'Anime',
    'Manga': 'Manga',
    'Music': 'Music',
    'Proxies': 'Proxies',
    'Partners': 'Partners',
    'Search...': 'Search...',
    'Settings': 'Settings',
    'English (Default)': 'English (Default)',
    'Spanish': 'Spanish',
    'French': 'French',
    'Russian': 'Russian',
    'Chinese (Simplified)': 'Chinese (Simplified)',
    'Japanese': 'Japanese',
    'Vietnamese': 'Vietnamese',
    'German': 'German',
    'Italian': 'Italian',
    'Portuguese': 'Portuguese',
    'Records Found': 'Records Found',
    'No matches': 'No matches',
    'New Stuff': 'New Stuff',
    'All Categories': 'All Categories',
    'SEARCH ARCHIVE': 'SEARCH ARCHIVE',
    'INITIALIZE STREAM': 'INITIALIZE STREAM',
    'Watch:': 'Watch:',
    'External Link Warning': 'External Link Warning',
    'Abort': 'Abort',
    'Proceed': 'Proceed',
    'Visit Site': 'Visit Site',
    'DECRYPTING WIKI...': 'DECRYPTING WIKI...',
    'FETCH WIKI INTELLIGENCE': 'FETCH WIKI INTELLIGENCE',
    'Direct Feed Offline • Initiating Search Protocol': 'Direct Feed Offline • Initiating Search Protocol',
    'The team behind ChillZone.': 'The team behind ChillZone.',
    'Click on our cards': 'Click on our cards',
    'to visit our personal sites and socials!': 'to visit our personal sites and socials!',
    'Click Which Ever Donation App U Want To Donate On': 'Click Which Ever Donation App U Want To Donate On',
    'Instant Transfer': 'Instant Transfer',
    'Mobile Payment': 'Mobile Payment',
    'Direct Transfer': 'Direct Transfer',
    'SOURCE': 'SOURCE',
    'You are about to leave Chillzone to view': 'You are about to leave Chillzone to view',
    'socials. Proceed with caution.': 'socials. Proceed with caution.',
    'Account': 'Account',
    'Manage your account settings.': 'Manage your account settings.',
    'Danger Zone': 'Danger Zone',
    'Delete Account': 'Delete Account',
    'This action is permanent and cannot be undone.': 'This action is permanent and cannot be undone.',
    'Type "DELETE" to confirm': 'Type "DELETE" to confirm',
    'Confirm Deletion': 'Confirm Deletion',
    'Cancel': 'Cancel',
    'Deleting...': 'Deleting...',
    'Display Name': 'Display Name',
    'Update': 'Update',
    'Updated': 'Updated',
    'Last changed:': 'Last changed:'
  },
  'es-ES': {
    'Theme': 'Tema',
    'Cloak': 'Disfraz',
    'Language': 'Idioma',
    'Changes apply instantly.': 'Los cambios se aplican al instante.',
    'Theme Name': 'Nombre del Tema',
    'Background': 'Fondo',
    'Foreground': 'Primer Plano',
    'Card': 'Tarjeta',
    'Border': 'Borde',
    'Primary': 'Primario',
    'Accent': 'Acento',
    'Reset to Default': 'Restablecer por Defecto',
    'Cloak Methods': 'Métodos de Disfraz',
    'Hide your activity in an about:blank tab.': 'Oculta tu actividad en una pestaña about:blank.',
    'Cloak Site': 'Sitio de Disfraz',
    'Tab Title': 'Título de Pestaña',
    'Tab Icon (URL)': 'Icono de Pestaña (URL)',
    'Open Now': 'Abrir Ahora',
    'Pick your preferred locale for time formatting and future language support.': 'Elige tu configuración regional preferida para el formato de hora y soporte futuro de idiomas.',
    'English is the default. Other options adjust locale formatting.': 'El inglés es el predeterminado. Otras opciones ajustan el formato regional.',
    'Military Time': 'Hora Militar',
    'Uses 24-hour clock format for the time widget.': 'Usa el formato de reloj de 24 horas para el widget de la hora.',
    'Time Zone': 'Zona Horaria',
    'Select a specific time zone or use your system default.': 'Selecciona una zona horaria específica o usa la predeterminada de tu sistema.',
    'Custom': 'Personalizado',
    'Default': 'Por Defecto',
    'System Default': 'Predeterminado del Sistema',
    'Home': 'Inicio',
    'Devs': 'Desarrolladores',
    'Donate': 'Donar',
    'Movies': 'Películas',
    'TV Shows': 'Series TV',
    'Animes': 'Animes',
    'Mangas': 'Mangas',
    'Anime': 'Anime',
    'Manga': 'Manga',
    'Music': 'Música',
    'Proxies': 'Proxies',
    'Partners': 'Socios',
    'Search...': 'Buscar...',
    'Settings': 'Ajustes',
    'English (Default)': 'Inglés (Predeterminado)',
    'Spanish': 'Español',
    'French': 'Francés',
    'Russian': 'Ruso',
    'Chinese (Simplified)': 'Chino (Simplificado)',
    'Japanese': 'Japonés',
    'Vietnamese': 'Vietnamita',
    'German': 'Alemán',
    'Italian': 'Italiano',
    'Portuguese': 'Portugués',
    'Records Found': 'Registros Encontrados',
    'No matches': 'Sin coincidencias',
    'All Categories': 'Todas las Categorías',
    'SEARCH ARCHIVE': 'BUSCAR EN ARCHIVO',
    'INITIALIZE STREAM': 'INICIALIZAR TRANSMISIÓN',
    'Watch:': 'Ver:',
    'External Link Warning': 'Advertencia de Enlace Externo',
    'Abort': 'Abortar',
    'Proceed': 'Proceder',
    'Visit Site': 'Visitar Sitio',
    'DECRYPTING WIKI...': 'DESCRIPTANDO WIKI...',
    'FETCH WIKI INTELLIGENCE': 'OBTENER INTELIGENCIA WIKI',
    'Direct Feed Offline • Initiating Search Protocol': 'Transmisión Directa Fuera de Línea • Iniciando Protocolo de Búsqueda',
    'The team behind ChillZone.': 'El equipo detrás de ChillZone.',
    'Click on our cards': 'Haz clic en nuestras tarjetas',
    'to visit our personal sites and socials!': 'para visitar nuestros sitios personales y redes sociales!',
    'Click Which Ever Donation App U Want To Donate On': 'Haz clic en la aplicación de donación que prefieras',
    'Instant Transfer': 'Transferencia Instantánea',
    'Mobile Payment': 'Pago Móvil',
    'Direct Transfer': 'Transferencia Directa',
    'SOURCE': 'FUENTE',
    'You are about to leave Chillzone to view': 'Estás a punto de salir de Chillzone para ver',
    'socials. Proceed with caution.': 'redes sociales. Procede con precaución.',
    'Account': 'Cuenta',
    'Manage your account settings.': 'Administra la configuración de tu cuenta.',
    'Danger Zone': 'Zona de Peligro',
    'Delete Account': 'Eliminar Cuenta',
    'This action is permanent and cannot be undone.': 'Esta acción es permanente y no se puede deshacer.',
    'Type "DELETE" to confirm': 'Escribe "DELETE" para confirmar',
    'Confirm Deletion': 'Confirmar Eliminación',
    'Cancel': 'Cancelar',
    'Deleting...': 'Eliminando...'
  },
  'fr-FR': {
    'Theme': 'Thème',
    'Cloak': 'Cape',
    'Language': 'Langue',
    'Changes apply instantly.': 'Les modifications s\'appliquent instantanément.',
    'Theme Name': 'Nom du Thème',
    'Background': 'Arrière-plan',
    'Foreground': 'Premier plan',
    'Card': 'Carte',
    'Border': 'Bordure',
    'Primary': 'Primaire',
    'Accent': 'Accent',
    'Reset to Default': 'Réinitialiser par défaut',
    'Cloak Methods': 'Méthodes de Cape',
    'Hide your activity in an about:blank tab.': 'Cachez votre activité dans un onglet about:blank.',
    'Cloak Site': 'Site de Cape',
    'Tab Title': 'Titre de l\'onglet',
    'Tab Icon (URL)': 'Icône de l\'onglet (URL)',
    'Open Now': 'Ouvrir maintenant',
    'Pick your preferred locale for time formatting and future language support.': 'Choisissez votre langue préférée pour le formatage de l\'heure et le support linguistique futur.',
    'English is the default. Other options adjust locale formatting.': 'L\'anglais est la langue par défaut. Les autres options ajustent le formatage local.',
    'Military Time': 'Heure Militaire',
    'Uses 24-hour clock format for the time widget.': 'Utilise le format 24 heures pour le widget de l\'heure.',
    'Time Zone': 'Fuseau Horaire',
    'Select a specific time zone or use your system default.': 'Sélectionnez un fuseau horaire spécifique ou utilisez celui de votre système.',
    'Custom': 'Personnalisé',
    'Default': 'Par défaut',
    'System Default': 'Système par défaut',
    'Home': 'Accueil',
    'Devs': 'Développeurs',
    'Donate': 'Faire un don',
    'Movies': 'Films',
    'TV Shows': 'Séries TV',
    'Animes': 'Animes',
    'Mangas': 'Mangas',
    'Anime': 'Anime',
    'Manga': 'Manga',
    'Music': 'Musique',
    'Proxies': 'Proxies',
    'Partners': 'Partenaires',
    'Search...': 'Rechercher...',
    'Settings': 'Paramètres',
    'English (Default)': 'Anglais (Par défaut)',
    'Spanish': 'Espagnol',
    'French': 'Français',
    'Russian': 'Russe',
    'Chinese (Simplified)': 'Chinois (Simplifié)',
    'Japanese': 'Japonais',
    'Vietnamese': 'Vietnamien',
    'German': 'Allemand',
    'Italian': 'Italien',
    'Portuguese': 'Portugais',
    'Records Found': 'Enregistrements trouvés',
    'No matches': 'Aucun résultat',
    'All Categories': 'Toutes les catégories',
    'SEARCH ARCHIVE': 'RECHERCHER DANS L\'ARCHIVE',
    'INITIALIZE STREAM': 'INITIALISER LE FLUX',
    'Watch:': 'Regarder:',
    'External Link Warning': 'Avertissement de lien externe',
    'Abort': 'Abandonner',
    'Proceed': 'Continuer',
    'Visit Site': 'Visiter le site',
    'DECRYPTING WIKI...': 'DÉCRYPTAGE DU WIKI...',
    'FETCH WIKI INTELLIGENCE': 'RÉCUPÉRER L\'INTELLIGENCE DU WIKI',
    'Direct Feed Offline • Initiating Search Protocol': 'Flux direct hors ligne • Initiation du protocole de recherche',
    'The team behind ChillZone.': 'L\'équipe derrière ChillZone.',
    'Click on our cards': 'Cliquez sur nos cartes',
    'to visit our personal sites and socials!': 'pour visiter nos sites personnels et réseaux sociaux !',
    'Click Which Ever Donation App U Want To Donate On': 'Cliquez sur l\'application de don de votre choix',
    'Instant Transfer': 'Transfert instantané',
    'Mobile Payment': 'Paiement mobile',
    'Direct Transfer': 'Transfert direct',
    'SOURCE': 'SOURCE',
    'You are about to leave Chillzone to view': 'Vous êtes sur le point de quitter Chillzone pour voir',
    'socials. Proceed with caution.': 'les réseaux sociaux. Procédez avec prudence.'
  },
  'zh-CN': {
    'Theme': '主题',
    'Cloak': '伪装',
    'Language': '语言',
    'Changes apply instantly.': '更改立即生效。',
    'Theme Name': '主题名称',
    'Background': '背景',
    'Foreground': '前景',
    'Card': '卡片',
    'Border': '边框',
    'Primary': '主要',
    'Accent': '强调',
    'Reset to Default': '重置为默认',
    'Cloak Methods': '伪装方法',
    'Hide your activity in an about:blank tab.': '在 about:blank 标签页中隐藏您的活动。',
    'Cloak Site': '伪装网站',
    'Tab Title': '标签标题',
    'Tab Icon (URL)': '标签图标 (URL)',
    'Open Now': '立即打开',
    'Pick your preferred locale for time formatting and future language support.': '选择您偏好的时间格式和未来语言支持的区域设置。',
    'English is the default. Other options adjust locale formatting.': '英语是默认语言。其他选项会调整区域格式。',
    'Military Time': '军事时间',
    'Uses 24-hour clock format for the time widget.': '时间小部件使用 24 小时制。',
    'Time Zone': '时区',
    'Select a specific time zone or use your system default.': '选择特定时区或使用系统默认设置。',
    'Custom': '自定义',
    'Default': '默认',
    'System Default': '系统默认',
    'Home': '首页',
    'Devs': '开发者',
    'Donate': '捐赠',
    'Movies': '电影',
    'TV Shows': '电视剧',
    'Animes': '动漫',
    'Mangas': '漫画',
    'Anime': '动漫',
    'Manga': '漫画',
    'Music': '音乐',
    'Proxies': '代理',
    'Partners': '合作伙伴',
    'Search...': '搜索...',
    'Settings': '设置',
    'English (Default)': '英语 (默认)',
    'Spanish': '西班牙语',
    'French': '法语',
    'Russian': '俄语',
    'Chinese (Simplified)': '中文 (简体)',
    'Japanese': '日语',
    'Vietnamese': '越南语',
    'German': '德语',
    'Italian': '意大利语',
    'Portuguese': '葡萄牙语',
    'Records Found': '找到记录',
    'No matches': '无匹配项',
    'All Categories': '所有类别',
    'SEARCH ARCHIVE': '搜索存档',
    'INITIALIZE STREAM': '初始化流',
    'Watch:': '观看:',
    'External Link Warning': '外部链接警告',
    'Abort': '中止',
    'Proceed': '继续',
    'Visit Site': '访问网站',
    'DECRYPTING WIKI...': '正在解密百科...',
    'FETCH WIKI INTELLIGENCE': '获取百科情报',
    'Direct Feed Offline • Initiating Search Protocol': '直接馈送离线 • 启动搜索协议',
    'The team behind ChillZone.': 'ChillZone 背后的团队。',
    'Click on our cards': '点击我们的卡片',
    'to visit our personal sites and socials!': '访问我们的个人网站和社交媒体！',
    'Click Which Ever Donation App U Want To Donate On': '点击您想要捐赠的任何捐赠应用',
    'Instant Transfer': '即时转账',
    'Mobile Payment': '移动支付',
    'Direct Transfer': '直接转账',
    'SOURCE': '来源',
    'You are about to leave Chillzone to view': '您即将离开 Chillzone 查看',
    'socials. Proceed with caution.': '的社交媒体。请谨慎操作。'
  },
  'ja-JP': {
    'Theme': 'テーマ',
    'Cloak': 'クローク',
    'Language': '言語',
    'Changes apply instantly.': '変更は即座に適用されます。',
    'Theme Name': 'テーマ名',
    'Background': '背景',
    'Foreground': '前景',
    'Card': 'カード',
    'Border': 'ボーダー',
    'Primary': 'プライマリ',
    'Accent': 'アクセント',
    'Reset to Default': 'デフォルトに戻す',
    'Cloak Methods': 'クローク方法',
    'Hide your activity in an about:blank tab.': 'about:blank タブでアクティビティを非表示にします。',
    'Cloak Site': 'クロークサイト',
    'Tab Title': 'タブのタイトル',
    'Tab Icon (URL)': 'タブアイコン (URL)',
    'Open Now': '今すぐ開く',
    'Pick your preferred locale for time formatting and future language support.': '時間形式と将来の言語サポートのために、お好みのロケールを選択してください。',
    'English is the default. Other options adjust locale formatting.': '英語がデフォルトです。他のオプションはロケール形式を調整します。',
    'Military Time': '24時間制',
    'Uses 24-hour clock format for the time widget.': '時間ウィジェットに24時間形式を使用します。',
    'Time Zone': 'タイムゾーン',
    'Select a specific time zone or use your system default.': '特定のタイムゾーンを選択するか、システムデフォルトを使用します。',
    'Custom': 'カスタム',
    'Default': 'デフォルト',
    'System Default': 'システムデフォルト',
    'Home': 'ホーム',
    'Devs': '開発者',
    'Donate': '寄付',
    'Movies': '映画',
    'TV Shows': 'テレビ番組',
    'Animes': 'アニメ',
    'Mangas': '漫画',
    'Anime': 'アニメ',
    'Manga': '漫画',
    'Music': '音楽',
    'Proxies': 'プロキシ',
    'Partners': 'パートナー',
    'Search...': '検索...',
    'Settings': '設定',
    'English (Default)': '英語 (デフォルト)',
    'Spanish': 'スペイン語',
    'French': 'フランス語',
    'Russian': 'ロシア語',
    'Chinese (Simplified)': '中国語 (簡体字)',
    'Japanese': '日本語',
    'Vietnamese': 'ベトナム語',
    'German': 'ドイツ語',
    'Italian': 'イタリア語',
    'Portuguese': 'ポルトガル語',
    'Records Found': '件の記録が見つかりました',
    'No matches': '一致なし',
    'All Categories': 'すべてのカテゴリ',
    'SEARCH ARCHIVE': 'アーカイブを検索',
    'INITIALIZE STREAM': 'ストリームを初期化',
    'Watch:': '視聴:',
    'External Link Warning': '外部リンクの警告',
    'Abort': '中止',
    'Proceed': '続行',
    'Visit Site': 'サイトにアクセス',
    'DECRYPTING WIKI...': 'Wikiを解読中...',
    'FETCH WIKI INTELLIGENCE': 'Wikiインテリジェンスを取得',
    'Direct Feed Offline • Initiating Search Protocol': 'ダイレクトフィードオフライン • 検索プロトコルを開始中',
    'The team behind ChillZone.': 'ChillZoneの背後にあるチーム。',
    'Click on our cards': 'カードをクリックして',
    'to visit our personal sites and socials！': '私たちの個人サイトやSNSにアクセスしてください！',
    'Click Which Ever Donation App U Want To Donate On': '寄付したいアプリをクリックしてください',
    'Instant Transfer': '即時送金',
    'Mobile Payment': 'モバイル決済',
    'Direct Transfer': '直接送金',
    'SOURCE': 'ソース',
    'You are about to leave Chillzone to view': 'Chillzoneを離れて',
    'socials. Proceed with caution.': 'のSNSを表示しようとしています。注意して続行してください。'
  },
  'de-DE': {
    'Theme': 'Thema',
    'Cloak': 'Tarnung',
    'Language': 'Sprache',
    'Changes apply instantly.': 'Änderungen werden sofort übernommen.',
    'Theme Name': 'Themenname',
    'Background': 'Hintergrund',
    'Foreground': 'Vordergrund',
    'Card': 'Karte',
    'Border': 'Rand',
    'Primary': 'Primär',
    'Accent': 'Akzent',
    'Reset to Default': 'Auf Standard zurücksetzen',
    'Cloak Methods': 'Tarnungsmethoden',
    'Hide your activity in an about:blank tab.': 'Verbergen Sie Ihre Aktivitäten in einem about:blank Tab.',
    'Cloak Site': 'Tarnungsseite',
    'Tab Title': 'Tab-Titel',
    'Tab Icon (URL)': 'Tab-Icon (URL)',
    'Open Now': 'Jetzt öffnen',
    'Pick your preferred locale for time formatting and future language support.': 'Wählen Sie Ihr bevorzugtes Gebietsschema für die Zeitformatierung und zukünftige Sprachunterstützung.',
    'English is the default. Other options adjust locale formatting.': 'Englisch ist der Standard. Andere Optionen passen die lokale Formatierung an.',
    'Military Time': 'Militärzeit',
    'Uses 24-hour clock format for the time widget.': 'Verwendet das 24-Stunden-Format für das Zeit-Widget.',
    'Time Zone': 'Zeitzone',
    'Select a specific time zone or use your system default.': 'Wählen Sie eine bestimmte Zeitzone oder verwenden Sie Ihren Systemstandard.',
    'Custom': 'Benutzerdefiniert',
    'Default': 'Standard',
    'System Default': 'Systemstandard',
    'Home': 'Startseite',
    'Devs': 'Entwickler',
    'Donate': 'Spenden',
    'Movies': 'Filme',
    'TV Shows': 'TV-Serien',
    'Animes': 'Animes',
    'Mangas': 'Mangas',
    'Anime': 'Anime',
    'Manga': 'Manga',
    'Music': 'Musik',
    'Proxies': 'Proxies',
    'Partners': 'Partner',
    'Search...': 'Suchen...',
    'Settings': 'Einstellungen',
    'English (Default)': 'Englisch (Standard)',
    'Spanish': 'Spanisch',
    'French': 'Französisch',
    'Russian': 'Russisch',
    'Chinese (Simplified)': 'Chinesisch (Vereinfacht)',
    'Japanese': 'Japanisch',
    'Vietnamese': 'Vietnamesisch',
    'German': 'Deutsch',
    'Italian': 'Italienisch',
    'Portuguese': 'Portugiesisch',
    'Records Found': 'Datensätze gefunden',
    'No matches': 'Keine Treffer',
    'All Categories': 'Alle Kategorien',
    'SEARCH ARCHIVE': 'ARCHIV DURCHSUCHEN',
    'INITIALIZE STREAM': 'STREAM INITIALISIEREN',
    'Watch:': 'Ansehen:',
    'External Link Warning': 'Warnung vor externem Link',
    'Abort': 'Abbrechen',
    'Proceed': 'Fortfahren',
    'Visit Site': 'Seite besuchen',
    'DECRYPTING WIKI...': 'WIKI WIRD ENTSCHLÜSSELT...',
    'FETCH WIKI INTELLIGENCE': 'WIKI-INTELLIGENZ ABRUFEN',
    'Direct Feed Offline • Initiating Search Protocol': 'Direkt-Feed offline • Suchprotokoll wird initiiert',
    'The team behind ChillZone.': 'Das Team hinter ChillZone.',
    'Click on our cards': 'Klicken Sie auf unsere Karten',
    'to visit our personal sites and socials!': 'um unsere persönlichen Seiten und sozialen Netzwerke zu besuchen!',
    'Click Which Ever Donation App U Want To Donate On': 'Klicken Sie auf die Spenden-App, über die Sie spenden möchten',
    'Instant Transfer': 'Sofortüberweisung',
    'Mobile Payment': 'Mobiles Bezahlen',
    'Direct Transfer': 'Direktüberweisung',
    'SOURCE': 'QUELLE',
    'You are about to leave Chillzone to view': 'Sie sind im Begriff, Chillzone zu verlassen, um',
    'socials. Proceed with caution.': 'soziale Netzwerke anzusehen. Gehen Sie mit Vorsicht vor.'
  },
  'it-IT': {
    'Theme': 'Tema',
    'Cloak': 'Mantello',
    'Language': 'Lingua',
    'Changes apply instantly.': 'Le modifiche si applicano istantaneamente.',
    'Theme Name': 'Nome del Tema',
    'Background': 'Sfondo',
    'Foreground': 'Primo Piano',
    'Card': 'Scheda',
    'Border': 'Bordo',
    'Primary': 'Primario',
    'Accent': 'Accento',
    'Reset to Default': 'Ripristina Predefiniti',
    'Cloak Methods': 'Metodi di Occultamento',
    'Hide your activity in an about:blank tab.': 'Nascondi la tua attività in una scheda about:blank.',
    'Cloak Site': 'Sito Occultato',
    'Tab Title': 'Titolo della Scheda',
    'Tab Icon (URL)': 'Icona della Scheda (URL)',
    'Open Now': 'Apri Ora',
    'Pick your preferred locale for time formatting and future language support.': 'Scegli la tua lingua preferita per il formato dell\'ora e il supporto linguistico futuro.',
    'English is the default. Other options adjust locale formatting.': 'L\'inglese è predefinito. Altre opzioni regolano la formattazione locale.',
    'Military Time': 'Ora Militare',
    'Uses 24-hour clock format for the time widget.': 'Usa il formato a 24 ore per il widget dell\'ora.',
    'Time Zone': 'Fuso Orario',
    'Select a specific time zone or use your system default.': 'Seleziona un fuso orario specifico o usa quello predefinito del sistema.',
    'Custom': 'Personalizzato',
    'Default': 'Predefinito',
    'System Default': 'Predefinito di Sistema',
    'Home': 'Home',
    'Devs': 'Sviluppatori',
    'Donate': 'Dona',
    'Movies': 'Film',
    'TV Shows': 'Serie TV',
    'Animes': 'Anime',
    'Mangas': 'Manga',
    'Anime': 'Anime',
    'Manga': 'Manga',
    'Music': 'Musica',
    'Proxies': 'Proxy',
    'Partners': 'Partner',
    'Search...': 'Cerca...',
    'Settings': 'Impostazioni',
    'English (Default)': 'Inglese (Predefinito)',
    'Spanish': 'Spagnolo',
    'French': 'Francese',
    'Russian': 'Russo',
    'Chinese (Simplified)': 'Cinese (Semplificato)',
    'Japanese': 'Giapponese',
    'Vietnamese': 'Vietnamita',
    'German': 'Tedesco',
    'Italian': 'Italiano',
    'Portuguese': 'Portoghese',
    'Records Found': 'Record trovati',
    'No matches': 'Nessuna corrispondenza',
    'All Categories': 'Tutte le categorie',
    'SEARCH ARCHIVE': 'CERCA NELL\'ARCHIVIO',
    'INITIALIZE STREAM': 'INIZIALIZZA STREAM',
    'Watch:': 'Guarda:',
    'External Link Warning': 'Avviso Link Esterno',
    'Abort': 'Annulla',
    'Proceed': 'Procedi',
    'Visit Site': 'Visita il sito',
    'DECRYPTING WIKI...': 'DECRIPTAZIONE WIKI...',
    'FETCH WIKI INTELLIGENCE': 'OTTIENI INTELLIGENZA WIKI',
    'Direct Feed Offline • Initiating Search Protocol': 'Feed diretto offline • Avvio protocollo di ricerca',
    'The team behind ChillZone.': 'Il team dietro ChillZone.',
    'Click on our cards': 'Clicca sulle nostre schede',
    'to visit our personal sites and socials!': 'per visitare i nostri siti personali e i social!',
    'Click Which Ever Donation App U Want To Donate On': 'Clicca sull\'app di donazione che preferisci',
    'Instant Transfer': 'Trasferimento istantaneo',
    'Mobile Payment': 'Pagamento mobile',
    'Direct Transfer': 'Trasferimento diretto',
    'SOURCE': 'FONTE',
    'You are about to leave Chillzone to view': 'Stai per lasciare Chillzone per visualizzare',
    'socials. Proceed with caution.': 'i social. Procedi con cautela.'
  },
  'pt-BR': {
    'Theme': 'Tema',
    'Cloak': 'Disfarce',
    'Language': 'Idioma',
    'Changes apply instantly.': 'As alterações são aplicadas instantaneamente.',
    'Theme Name': 'Nome do Tema',
    'Background': 'Plano de Fundo',
    'Foreground': 'Primeiro Plano',
    'Card': 'Cartão',
    'Border': 'Borda',
    'Primary': 'Primário',
    'Accent': 'Destaque',
    'Reset to Default': 'Redefinir para o Padrão',
    'Cloak Methods': 'Métodos de Disfarce',
    'Hide your activity in an about:blank tab.': 'Oculte sua atividade em uma aba about:blank.',
    'Cloak Site': 'Site de Disfarce',
    'Tab Title': 'Título da Aba',
    'Tab Icon (URL)': 'Ícone da Aba (URL)',
    'Open Now': 'Abrir Agora',
    'Pick your preferred locale for time formatting and future language support.': 'Escolha seu local preferido para formatação de hora e suporte futuro a idiomas.',
    'English is the default. Other options adjust locale formatting.': 'Inglês é o padrão. Outras opções ajustam a formattação local.',
    'Military Time': 'Hora Militar',
    'Uses 24-hour clock format for the time widget.': 'Usa o formato de 24 horas para o widget de hora.',
    'Time Zone': 'Fuso Horário',
    'Select a specific time zone or use your system default.': 'Selecione um fuso horário específico ou use o padrão do sistema.',
    'Custom': 'Personalizado',
    'Default': 'Padrão',
    'System Default': 'Padrão do Sistema',
    'Home': 'Início',
    'Devs': 'Devs',
    'Donate': 'Doar',
    'Movies': 'Filmes',
    'TV Shows': 'Séries de TV',
    'Animes': 'Animes',
    'Mangas': 'Mangás',
    'Anime': 'Anime',
    'Manga': 'Mangá',
    'Music': 'Música',
    'Proxies': 'Proxies',
    'Partners': 'Parceiros',
    'Search...': 'Buscar...',
    'Settings': 'Configurações',
    'English (Default)': 'Inglês (Padrão)',
    'Spanish': 'Espanhol',
    'French': 'Francês',
    'Russian': 'Russo',
    'Chinese (Simplified)': 'Chinês (Simplificado)',
    'Japanese': 'Japonês',
    'Vietnamese': 'Vietnamita',
    'German': 'Alemão',
    'Italian': 'Italiano',
    'Portuguese': 'Português',
    'Records Found': 'Registros encontrados',
    'No matches': 'Sem correspondências',
    'All Categories': 'Todas as categorias',
    'SEARCH ARCHIVE': 'PESQUISAR ARQUIVO',
    'INITIALIZE STREAM': 'INICIALIZAR STREAM',
    'Watch:': 'Assistir:',
    'External Link Warning': 'Aviso de Link Externo',
    'Abort': 'Abortar',
    'Proceed': 'Prosseguir',
    'Visit Site': 'Visitar Site',
    'DECRYPTING WIKI...': 'DESCRIPTOGRAFANDO WIKI...',
    'FETCH WIKI INTELLIGENCE': 'OBTER INTELIGÊNCIA DA WIKI',
    'Direct Feed Offline • Initiating Search Protocol': 'Feed direto offline • Iniciando protocolo de pesquisa',
    'The team behind ChillZone.': 'A equipe por trás do ChillZone.',
    'Click on our cards': 'Clique em nossos cartões',
    'to visit our personal sites and socials!': 'para visitar nossos sites pessoais e redes sociais!',
    'Click Which Ever Donation App U Want To Donate On': 'Clique no aplicativo de doação que você deseja usar',
    'Instant Transfer': 'Transferência Instantânea',
    'Mobile Payment': 'Pagamento Móvel',
    'Direct Transfer': 'Transferência Direta',
    'SOURCE': 'FONTE',
    'You are about to leave Chillzone to view': 'Você está prestes a sair do Chillzone para ver',
    'socials. Proceed with caution.': 'redes sociais. Prossiga com cautela.'
  }
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  militaryTime: boolean;
  setMilitaryTime: (val: boolean) => void;
  timeZone: string;
  setTimeZone: (tz: string) => void;
  t: (key: string) => string;
  translateDynamic: (text: string) => Promise<string>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState(localStorage.getItem('chillzone_language') || 'en-US');
  const [militaryTime, setMilitaryTimeState] = useState(localStorage.getItem('chillzone_military_time') === 'true');
  const [timeZone, setTimeZoneState] = useState(localStorage.getItem('chillzone_timezone') || 'auto');
  const [dynamicCache, setDynamicCache] = useState<Record<string, string>>(() => {
    const saved = localStorage.getItem('chillzone_translation_cache');
    return saved ? JSON.parse(saved) : {};
  });

  useEffect(() => {
    localStorage.setItem('chillzone_translation_cache', JSON.stringify(dynamicCache));
  }, [dynamicCache]);

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    localStorage.setItem('chillzone_language', lang);
    window.dispatchEvent(new Event('chillzone_settings_changed'));
  };

  const setMilitaryTime = (val: boolean) => {
    setMilitaryTimeState(val);
    localStorage.setItem('chillzone_military_time', val.toString());
    window.dispatchEvent(new Event('chillzone_settings_changed'));
  };

  const setTimeZone = (tz: string) => {
    setTimeZoneState(tz);
    localStorage.setItem('chillzone_timezone', tz);
    window.dispatchEvent(new Event('chillzone_settings_changed'));
  };

  const t = (key: string) => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS['en-US'];
    return langDict[key] || TRANSLATIONS['en-US'][key] || key;
  };

  const translateDynamic = async (text: string) => {
    if (!text || language === 'en-US') return text;
    
    const cacheKey = `${language}:${text}`;
    if (dynamicCache[cacheKey]) return dynamicCache[cacheKey];

    // Check localStorage directly for faster access if state hasn't updated yet
    const savedCache = JSON.parse(localStorage.getItem('chillzone_translation_cache') || '{}');
    if (savedCache[cacheKey]) return savedCache[cacheKey];

    try {
      const translated = await translateText(text, language);
      setDynamicCache(prev => ({ ...prev, [cacheKey]: translated }));
      return translated;
    } catch (error) {
      console.error("Translation error:", error);
      return text;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, militaryTime, setMilitaryTime, timeZone, setTimeZone, t, translateDynamic }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
